/* Unique creature addr→fn tables, generated once from the former CallEnemyAi /
 * CallEnemyPreInstr / CallEnemyInstr / CallHitboxShot switches.
 *
 * Drain plan: as creature files grow C vtables, delete rows here. Gameplay AI
 * is bound at EnemyDef load; these tables are leftover unique lookup for load,
 * hitbox, and instruction bytecode — not a per-frame 24-bit ROM-address switch.
 */
#include "enemy_ai_canon.h"
#include "ida_types.h"
#include "variables.h"
#include "funcs.h"
#include "sm_rtl.h"
#include "enemy_types.h"
#include <stdlib.h>

static void EnemyAi_Nop(void) {}
static void EnemyPreInstr_Nop(uint16 k) { (void)k; }

/* Thunks for unique handlers that take cur_enemy_index / collision index. */
static void ai_thunk_Rinka_Frozen(void) { Rinka_Frozen(cur_enemy_index); }
static void ai_thunk_Rinka_Powerbomb(void) { Rinka_Powerbomb(cur_enemy_index); }
static void ai_thunk_Fireflea_Touch(void) { Fireflea_Touch(cur_enemy_index); }
static void ai_thunk_Metroid_Powerbomb(void) { Metroid_Powerbomb(cur_enemy_index); }
static void ai_thunk_MotherBrainsTubesFalling_Main(void) { MotherBrainsTubesFalling_Main(cur_enemy_index); }
static void ai_thunk_Kraid_Arm_Shot(void) { Kraid_Arm_Shot(collision_detection_index * 2); }

/* Pre-instr handlers declared void(void). */
static void pre_thunk_NorfairLavaMan_Func_13(uint16 k) { (void)k; NorfairLavaMan_Func_13(); }

typedef struct EnemyAiAddrMap {
  uint32 addr;
  EnemyAiFn fn;
} EnemyAiAddrMap;

static const EnemyAiAddrMap kEnemyAiByAddr[] = {
  { fnEnemy_GrappleReact_NoInteract_A0, Enemy_GrappleReact_NoInteract_A0 },
  { fnEnemy_GrappleReact_SamusLatchesOn_A0, Enemy_GrappleReact_SamusLatchesOn_A0 },
  { fnEnemy_GrappleReact_KillEnemy_A0, Enemy_GrappleReact_KillEnemy_A0 },
  { fnEnemy_GrappleReact_CancelBeam_A0, Enemy_GrappleReact_CancelBeam_A0 },
  { fnEnemy_GrappleReact_SamusLatchesNoInvinc_A0, Enemy_GrappleReact_SamusLatchesNoInvinc_A0 },
  { fnEnemy_GrappleReact_SamusLatchesParalyze_A0, Enemy_GrappleReact_SamusLatchesParalyze_A0 },
  { fnEnemy_GrappleReact_HurtSamus_A0, Enemy_GrappleReact_HurtSamus_A0 },
  { fnEnemy_NormalTouchAI_A0, Enemy_NormalTouchAI_A0 },
  { 0xA08028, Enemy_NormalTouchAI_SkipDeathAnim_A0 },
  { fnEnemy_NormalShotAI_A0, Enemy_NormalShotAI_A0 },
  { 0xA08032, Enemy_NormalShotAI_SkipSomeParts_A0 },
  { fnEnemy_NormalPowerBombAI_A0, NormalEnemyPowerBombAi },
  { 0xA0803C, Enemy_NormalPowerBombAI_SkipDeathAnim_A0 },
  { fnEnemy_NormalFrozenAI, Enemy_NormalFrozenAI },
  { fnCreateADudShot, CreateADudShot },
  { fnnullsub_169, EnemyAi_Nop },
  { fnnullsub_170, EnemyAi_Nop },
  { fnBouncingGoofball_Init, BouncingGoofball_Init },
  { fnBouncingGoofball_Main, BouncingGoofball_Main },
  { fnMiniCrocomire_Init, MiniCrocomire_Init },
  { fnMiniCrocomire_Main, MiniCrocomire_Main },
  { fnMaridiaBeybladeTurtle_Init, MaridiaBeybladeTurtle_Init },
  { fnMiniMaridiaBeybladeTurtle_Init, MiniMaridiaBeybladeTurtle_Init },
  { fnMaridiaBeybladeTurtle_Main, MaridiaBeybladeTurtle_Main },
  { fnMiniMaridiaBeybladeTurtle_Main, MiniMaridiaBeybladeTurtle_Main },
  { fnMaridiaBeybladeTurtle_Touch, MaridiaBeybladeTurtle_Touch },
  { fnMiniMaridiaBeybladeTurtle_Touch, MiniMaridiaBeybladeTurtle_Touch },
  { fnMiniMaridiaBeybladeTurtle_Shot, MiniMaridiaBeybladeTurtle_Shot },
  { fnThinHoppingBlobs_Init, ThinHoppingBlobs_Init },
  { fnThinHoppingBlobs_Main, ThinHoppingBlobs_Main },
  { fnSpikeShootingPlant_Init, SpikeShootingPlant_Init },
  { fnSpikeShootingPlant_Main, SpikeShootingPlant_Main },
  { fnMaridiaSpikeyShell_Init, MaridiaSpikeyShell_Init },
  { fnMaridiaSpikeyShell_Main, MaridiaSpikeyShell_Main },
  { fnMaridiaSpikeyShell_Shot, MaridiaSpikeyShell_Shot },
  { fnGunshipTop_Init, GunshipTop_Init },
  { fnGunshipBottom_Init, GunshipBottom_Init },
  { fnGunshipTop_Main, GunshipTop_Main },
  { fnFlies_Init, Flies_Init },
  { fnFlies_Main, Flies_Main },
  { fnNorfairErraticFireball_Init, NorfairErraticFireball_Init },
  { fnNorfairErraticFireball_Main, NorfairErraticFireball_Main },
  { fnLavaquakeRocks_Init, LavaquakeRocks_Init },
  { fnLavaquakeRocks_Main, LavaquakeRocks_Main },
  { fnRinka_Init, Rinka_Init },
  { fnRinka_Main, Rinka_Main },
  { fnRinka_Frozen, ai_thunk_Rinka_Frozen },
  { fnRinka_Touch, Rinka_Touch },
  { fnRinka_Shot, Rinka_Shot },
  { fnRinka_Powerbomb, ai_thunk_Rinka_Powerbomb },
  { fnRio_Init, Rio_Init },
  { fnRio_Main, Rio_Main },
  { fnNorfairLavajumpingEnemy_Init, NorfairLavajumpingEnemy_Init },
  { fnNorfairLavajumpingEnemy_Main, NorfairLavajumpingEnemy_Main },
  { fnNorfairRio_Init, NorfairRio_Init },
  { fnNorfairRio_Main, NorfairRio_Main },
  { fnLowerNorfairRio_Init, LowerNorfairRio_Init },
  { fnLowerNorfairRio_Main, LowerNorfairRio_Main },
  { fnMaridiaLargeSnail_Init, MaridiaLargeSnail_Init },
  { fnMaridiaLargeSnail_Main, MaridiaLargeSnail_Main },
  { fnMaridiaLargeSnail_Touch, MaridiaLargeSnail_Touch },
  { fnMaridiaLargeSnail_Shot, MaridiaLargeSnail_Shot },
  { fnHirisingSlowfalling_Init, HirisingSlowfalling_Init },
  { fnHirisingSlowfalling_Main, HirisingSlowfalling_Main },
  { fnGripper_Init, Gripper_Init },
  { fnGripper_Main, Gripper_Main },
  { fnJetPowerRipper_Init, JetPowerRipper_Init },
  { fnJetPowerRipper_Main, JetPowerRipper_Main },
  { fnJetPowerRipper_Shot, JetPowerRipper_Shot },
  { fnRipper_Init, Ripper_Init },
  { fnRipper_Main, Ripper_Main },
  { fnLavaSeahorse_Init, LavaSeahorse_Init },
  { fnLavaSeahorse_Main, LavaSeahorse_Main },
  { fnLavaSeahorse_Touch, LavaSeahorse_Touch },
  { fnLavaSeahorse_Shot, LavaSeahorse_Shot },
  { fnLavaSeahorse_Powerbomb, LavaSeahorse_Powerbomb },
  { fnTimedShutter_Init, TimedShutter_Init },
  { fnTimedShutter_Main, TimedShutter_Main },
  { fnRisingFallingPlatform_Init, RisingFallingPlatform_Init },
  { fnShootableShutter_Init, ShootableShutter_Init },
  { fnRisingFallingPlatform_Main, RisingFallingPlatform_Main },
  { fnRisingFallingPlatform_Touch, RisingFallingPlatform_Touch },
  { fnRisingFallingPlatform_Shot, RisingFallingPlatform_Shot },
  { fnShootableShutter_Shot, ShootableShutter_Shot },
  { fnRisingFallingPlatform_Powerbomb, RisingFallingPlatform_Powerbomb },
  { fnHorizontalShootableShutter_Init, HorizontalShootableShutter_Init },
  { fnHorizontalShootableShutter_Main, HorizontalShootableShutter_Main },
  { fnHorizontalShootableShutter_Touch, HorizontalShootableShutter_Touch },
  { fnHorizontalShootableShutter_Shot, HorizontalShootableShutter_Shot },
  { fnHorizontalShootableShutter_Powerbomb, HorizontalShootableShutter_Powerbomb },
  { fnWaver_Init, Waver_Init },
  { fnWaver_Main, Waver_Main },
  { fnMetalee_Init, Metalee_Init },
  { fnMetalee_Main, Metalee_Main },
  { fnMetalee_Shot, Metalee_Shot },
  { fnFireflea_Init, Fireflea_Init },
  { fnFireflea_Main, Fireflea_Main },
  { fnFireflea_Touch, ai_thunk_Fireflea_Touch },
  { fnFireflea_Powerbomb, Fireflea_Powerbomb },
  { fnFireflea_Shot, Fireflea_Shot },
  { fnMaridiaFish_Init, MaridiaFish_Init },
  { fnMaridiaFish_Main, MaridiaFish_Main },
  { fnElevator_Init, Elevator_Init },
  { fnElevator_Frozen, Elevator_Frozen },
  { fnCrab_Init, Crab_Init },
  { fnSlug_Init, Slug_Init },
  { fnPlatformThatFallsWithSamus_Init, PlatformThatFallsWithSamus_Init },
  { fnFastMovingSlowSinkingPlatform_Init, FastMovingSlowSinkingPlatform_Init },
  { fnPlatformThatFallsWithSamus_Main, PlatformThatFallsWithSamus_Main },
  { fnnullsub_32, EnemyAi_Nop },
  { fnFastMovingSlowSinkingPlatform_Shot, FastMovingSlowSinkingPlatform_Shot },
  { fnRoach_Init, Roach_Init },
  { fnRoach_Main, Roach_Main },
  { fnMochtroid_Init, Mochtroid_Init },
  { fnMochtroid_Main, Mochtroid_Main },
  { fnMochtroid_Touch, Mochtroid_Touch },
  { fnMochtroid_Shot, Mochtroid_Shot },
  { fnSidehopper_Init, Sidehopper_Init },
  { fnSidehopper_Main, Sidehopper_Main },
  { fnMaridiaRefillCandy_Init, MaridiaRefillCandy_Init },
  { fnMaridiaRefillCandy_Main, MaridiaRefillCandy_Main },
  { fnNorfairSlowFireball_Init, NorfairSlowFireball_Init },
  { fnBang_Init, Bang_Init },
  { fnBang_Main, Bang_Main },
  { fnBang_Shot, Bang_Shot },
  { fnSkree_Init, Skree_Init },
  { fnSkree_Main, Skree_Main },
  { fnSkree_Shot, Skree_Shot },
  { fnMaridiaSnail_Init, MaridiaSnail_Init },
  { fnMaridiaSnail_Main, MaridiaSnail_Main },
  { fnMaridiaSnail_Touch, MaridiaSnail_Touch },
  { fnMaridiaSnail_Shot, MaridiaSnail_Shot },
  { fnReflec_Init, Reflec_Init },
  { fnnullsub_33, EnemyAi_Nop },
  { fnReflec_Shot, Reflec_Shot },
  { fnWreckedShipOrangeZoomer_Init, WreckedShipOrangeZoomer_Init },
  { fnWreckedShipOrangeZoomer_Main, WreckedShipOrangeZoomer_Main },
  { fnBigEyeBugs_Init, BigEyeBugs_Init },
  { fnFireZoomer_Init, FireZoomer_Init },
  { fnStoneZoomer_Init, StoneZoomer_Init },
  { fnStoneZoomer_Main, StoneZoomer_Main },
  { fnMetroid_Init, Metroid_Init },
  { fnMetroid_Frozen, Metroid_Frozen },
  { fnMetroid_Hurt, Metroid_Hurt },
  { fnMetroid_Main, Metroid_Main },
  { fnMetroid_Touch, Metroid_Touch },
  { fnMetroid_Shot, Metroid_Shot },
  { fnMetroid_Powerbomb, ai_thunk_Metroid_Powerbomb },
  { fnCrocomire_Hurt, Crocomire_Hurt },
  { fnCrocomire_Init, Crocomire_Init },
  { fnCrocomire_Main, Crocomire_Main },
  { fnnullsub_34, EnemyAi_Nop },
  { fnCrocomire_Func_93, Crocomire_Func_93 },
  { fnCrocomire_Func_94, Crocomire_Func_94 },
  { fnCrocomire_Powerbomb, Crocomire_Powerbomb },
  { fnCrocomire_Func_95, Crocomire_Func_95 },
  { fnCrocomire_Func_1, Crocomire_Func_1 },
  { fnCrocomireTongue_Init, CrocomireTongue_Init },
  { fnCrocomireTongue_Main, CrocomireTongue_Main },
  { fnDraygon_Init, Draygon_Init },
  { fnDraygon_Main, Draygon_Main },
  { fnDraygon_Hurt, Draygon_Hurt },
  { fnDraygon_Touch, Draygon_Touch },
  { fnDraygon_Shot, Draygon_Shot },
  { fnDraygon_Powerbomb, Draygon_Powerbomb },
  { fnDraygonsEye_Init, DraygonsEye_Init },
  { fnDraygonsEye_Main, DraygonsEye_Main },
  { fnDraygonsTail_Init, DraygonsTail_Init },
  { fnnullsub_37, EnemyAi_Nop },
  { fnDraygonsArms_Init, DraygonsArms_Init },
  { fnnullsub_38, EnemyAi_Nop },
  { fnSporeSpawn_Init, SporeSpawn_Init },
  { fnSporeSpawn_Main, SporeSpawn_Main },
  { fnSporeSpawn_Shot, SporeSpawn_Shot },
  { fnSporeSpawn_Touch, SporeSpawn_Touch },
  { fnnullsub_39, EnemyAi_Nop },
  { fnBoulder_Init, Boulder_Init },
  { fnBoulder_Main, Boulder_Main },
  { fnSpikeyPlatform_Init, SpikeyPlatform_Init },
  { fnSpikeyPlatform2ndEnemy_Init, SpikeyPlatform2ndEnemy_Init },
  { fnSpikeyPlatform2ndEnemy_Main, SpikeyPlatform2ndEnemy_Main },
  { fnSpikeyPlatform_Main, SpikeyPlatform_Main },
  { fnFireGeyser_Init, FireGeyser_Init },
  { fnFireGeyser_Main, FireGeyser_Main },
  { fnNuclearWaffle_Init, NuclearWaffle_Init },
  { fnNuclearWaffle_Main, NuclearWaffle_Main },
  { fnFakeKraid_Init, FakeKraid_Init },
  { fnFakeKraid_Main, FakeKraid_Main },
  { fnFakeKraid_Touch, FakeKraid_Touch },
  { fnFakeKraid_Shot, FakeKraid_Shot },
  { fnCeresRidley_Init, CeresRidley_Init },
  { fnCeresRidley_Main, CeresRidley_Main },
  { fnCeresRidley_Hurt, CeresRidley_Hurt },
  { fnRidley_Main, Ridley_Main },
  { fnRidley_Func_2, Ridley_Func_2 },
  { fnRidley_Hurt, Ridley_Hurt },
  { fnRidleysExplosion_Init, RidleysExplosion_Init },
  { fnRidleysExplosion_Main, RidleysExplosion_Main },
  { fnRidley_Shot, Ridley_Shot },
  { fnRidley_Powerbomb, Ridley_Powerbomb },
  { fnCeresSteam_Init, CeresSteam_Init },
  { fnCeresSteam_Main, CeresSteam_Main },
  { fnCeresSteam_Touch, CeresSteam_Touch },
  { fnCeresDoor_Init, CeresDoor_Init },
  { fnCeresDoor_Main, CeresDoor_Main },
  { fnnullsub_41, EnemyAi_Nop },
  { fnZebetites_Init, Zebetites_Init },
  { fnZebetites_Main, Zebetites_Main },
  { fnZebetites_Touch, Zebetites_Touch },
  { fnZebetites_Shot, Zebetites_Shot },
  { fnnullsub_44, EnemyAi_Nop },
  { fnKraidsArm_Touch, KraidsArm_Touch },
  { fnKraid_Touch, Kraid_Touch },
  { fnnullsub_43, EnemyAi_Nop },
  { fnKraid_Arm_Shot, ai_thunk_Kraid_Arm_Shot },
  { fnKraid_Init, Kraid_Init },
  { fnKraidsArm_Init, KraidsArm_Init },
  { fnKraidsTopLint_Init, KraidsTopLint_Init },
  { fnKraidsMiddleLint_Init, KraidsMiddleLint_Init },
  { fnKraidsBottomLint_Init, KraidsBottomLint_Init },
  { fnKraidsFoot_Init, KraidsFoot_Init },
  { fnKraid_Main, Kraid_Main },
  { fnKraidsArm_Main, KraidsArm_Main },
  { fnKraidsTopLint_Main, KraidsTopLint_Main },
  { fnKraidsMiddleLint_Main, KraidsMiddleLint_Main },
  { fnKraidsBottomLint_Main, KraidsBottomLint_Main },
  { fnKraidsFoot_Main, KraidsFoot_Main },
  { fnKraidsGoodFingernail_Touch, KraidsGoodFingernail_Touch },
  { fnKraidsBadFingernail_Touch, KraidsBadFingernail_Touch },
  { fnKraidsGoodFingernail_Init, KraidsGoodFingernail_Init },
  { fnKraidsBadFingernail_Init, KraidsBadFingernail_Init },
  { fnKraidsGoodFingernail_Main, KraidsGoodFingernail_Main },
  { fnKraidsBadFingernail_Main, KraidsBadFingernail_Main },
  { fnPhantoon_Init, Phantoon_Init },
  { fnPhantoon2_Init, Phantoon2_Init },
  { fnPhantoon_Main, Phantoon_Main },
  { fnPhantoon_Hurt, Phantoon_Hurt },
  { fnPhantoon_Touch, Phantoon_Touch },
  { fnnullsub_358, EnemyAi_Nop },
  { fnPhantoon_Shot, Phantoon_Shot },
  { fnnullsub_45, EnemyAi_Nop },
  { fnEtecoon_Init, Etecoon_Init },
  { fnEtecoon_Main, Etecoon_Main },
  { fnDachora_Init, Dachora_Init },
  { fnDachora_Main, Dachora_Main },
  { fnMiniDraygon_Init, MiniDraygon_Init },
  { fnEvirProjectile_Init, EvirProjectile_Init },
  { fnMiniDraygon_Main, MiniDraygon_Main },
  { fnEvirProjectile_Main, EvirProjectile_Main },
  { fnMiniDraygon_Touch, MiniDraygon_Touch },
  { fnMiniDraygon_Powerbomb, MiniDraygon_Powerbomb },
  { fnMiniDraygon_Shot, MiniDraygon_Shot },
  { fnMorphBallEye_Init, MorphBallEye_Init },
  { fnMorphBallEye_Main, MorphBallEye_Main },
  { fnFune_Init, Fune_Init },
  { fnFune_Main, Fune_Main },
  { fnWreckedShipGhost_Init, WreckedShipGhost_Init },
  { fnWreckedShipGhost_Main, WreckedShipGhost_Main },
  { fnYappingMaw_Init, YappingMaw_Init },
  { fnYappingMaw_Main, YappingMaw_Main },
  { fnYappingMaw_Touch, YappingMaw_Touch },
  { fnYappingMaw_Shot, YappingMaw_Shot },
  { fnYappingMaw_Frozen, YappingMaw_Frozen },
  { fnKago_Init, Kago_Init },
  { fnKago_Main, Kago_Main },
  { fnKago_Shot, Kago_Shot },
  { fnNorfairLavaMan_Init, NorfairLavaMan_Init },
  { fnNorfairLavaMan_Main, NorfairLavaMan_Main },
  { fnNorfairLavaMan_Powerbomb, NorfairLavaMan_Powerbomb },
  { fnNorfairLavaMan_Touch, NorfairLavaMan_Touch },
  { fnNorfairLavaMan_Shot, NorfairLavaMan_Shot },
  { fnBeetom_Init, Beetom_Init },
  { fnBeetom_Main, Beetom_Main },
  { fnBeetom_Touch, Beetom_Touch },
  { fnBeetom_Shot, Beetom_Shot },
  { fnMaridiaFloater_Init, MaridiaFloater_Init },
  { fnMaridiaFloater_Main, MaridiaFloater_Main },
  { fnMaridiaFloater_Touch, MaridiaFloater_Touch },
  { fnMaridiaFloater_Shot, MaridiaFloater_Shot },
  { fnMaridiaFloater_Powerbomb, MaridiaFloater_Powerbomb },
  { fnWreckedShipRobot_Init, WreckedShipRobot_Init },
  { fnWreckedShipRobotDeactivated_Init, WreckedShipRobotDeactivated_Init },
  { fnWreckedShipRobot_Main, WreckedShipRobot_Main },
  { fnnullsub_342, EnemyAi_Nop },
  { fnWreckedShipRobotDeactivated_Touch, WreckedShipRobotDeactivated_Touch },
  { fnWreckedShipRobotDeactivated_Shot, WreckedShipRobotDeactivated_Shot },
  { fnWreckedShipRobot_Shot, WreckedShipRobot_Shot },
  { fnMaridiaPuffer_Init, MaridiaPuffer_Init },
  { fnMaridiaPuffer_Main, MaridiaPuffer_Main },
  { fnMaridiaPuffer_Shot, MaridiaPuffer_Shot },
  { fnWalkingLavaSeahorse_Init, WalkingLavaSeahorse_Init },
  { fnWalkingLavaSeahorse_Main, WalkingLavaSeahorse_Main },
  { fnWreckedShipOrbs_Init, WreckedShipOrbs_Init },
  { fnWreckedShipOrbs_Main, WreckedShipOrbs_Main },
  { fnWreckedShipSpark_Init, WreckedShipSpark_Init },
  { fnWreckedShipSpark_Main, WreckedShipSpark_Main },
  { fnWreckedShipSpark_Shot, WreckedShipSpark_Shot },
  { fnBlueBrinstarFaceBlock_Init, BlueBrinstarFaceBlock_Init },
  { fnBlueBrinstarFaceBlock_Main, BlueBrinstarFaceBlock_Main },
  { fnBlueBrinstarFaceBlock_Shot, BlueBrinstarFaceBlock_Shot },
  { fnKiHunter_Init, KiHunter_Init },
  { fnKiHunterWings_Init, KiHunterWings_Init },
  { fnKiHunter_Main, KiHunter_Main },
  { fnKiHunterWings_Main, KiHunterWings_Main },
  { fnKiHunter_Shot, KiHunter_Shot },
  { fnMotherBrainsBody_Init, MotherBrainsBody_Init },
  { fnMotherBrainsBrain_Init, MotherBrainsBrain_Init },
  { fnMotherBrainsBody_Hurt, MotherBrainsBody_Hurt },
  { fnMotherBrainsBody_Powerbomb, MotherBrainsBody_Powerbomb },
  { fnMotherBrainsBrain_Hurt, MotherBrainsBrain_Hurt },
  { fnMotherBrainsTubesFalling_Init, MotherBrainsTubesFalling_Init },
  { fnMotherBrainsTubesFalling_Main, ai_thunk_MotherBrainsTubesFalling_Main },
  { fnMotherBrainsBody_Shot, MotherBrainsBody_Shot },
  { fnMotherBrainsBrain_Shot, MotherBrainsBrain_Shot },
  { fnnullsub_47, EnemyAi_Nop },
  { fnMotherBrainsBrain_Touch, MotherBrainsBrain_Touch },
  { fnShitroidInCutscene_Init, ShitroidInCutscene_Init },
  { fnShitroidInCutscene_Main, ShitroidInCutscene_Main },
  { fnShitroidInCutscene_Touch, ShitroidInCutscene_Touch },
  { fnDeadTorizo_Init, DeadTorizo_Init },
  { fnDeadTorizo_Main, DeadTorizo_Main },
  { fnDeadTorizo_Powerbomb, DeadTorizo_Powerbomb },
  { fnDeadTorizo_Shot, DeadTorizo_Shot },
  { fnDeadSidehopper_Init, DeadSidehopper_Init },
  { fnDeadZoomer_Init, DeadZoomer_Init },
  { fnDeadRipper_Init, DeadRipper_Init },
  { fnDeadSkree_Init, DeadSkree_Init },
  { fnDeadSidehopper_Powerbomb, DeadSidehopper_Powerbomb },
  { fnDeadSidehopper_Main, DeadSidehopper_Main },
  { fnDeadZoomer_Powerbomb, DeadZoomer_Powerbomb },
  { fnDeadZoomer_Shot, DeadZoomer_Shot },
  { fnDeadRipper_Powerbomb, DeadRipper_Powerbomb },
  { fnDeadRipper_Shot, DeadRipper_Shot },
  { fnDeadSkree_Powerbomb, DeadSkree_Powerbomb },
  { fnDeadSkree_Shot, DeadSkree_Shot },
  { fnDeadSidehopper_Shot, DeadSidehopper_Shot },
  { fnDeadSidehopper_Touch, DeadSidehopper_Touch },
  { fnShitroid_Init, Shitroid_Init },
  { fnShitroid_Powerbomb, Shitroid_Powerbomb },
  { fnShitroid_Main, Shitroid_Main },
  { fnShitroid_Touch, Shitroid_Touch },
  { fnShitroid_Shot, Shitroid_Shot },
  { fnTorizo_Hurt, Torizo_Hurt },
  { fnTorizo_Main, Torizo_Main },
  { fnTorizo_Init, Torizo_Init },
  { fnGoldTorizo_Touch, GoldTorizo_Touch },
  { fnTorizo_Shot, Torizo_Shot },
  { fnnullsub_271, EnemyAi_Nop },
  { fnTorizo_Func_8, Torizo_Func_8 },
  { fnGoldTorizo_Main, GoldTorizo_Main },
  { fnGoldTorizo_Hurt, GoldTorizo_Hurt },
  { fnGoldTorizo_Shot, GoldTorizo_Shot },
  { fnnullsub_49, EnemyAi_Nop },
  { fnTourianEntranceStatue_Init, TourianEntranceStatue_Init },
  { fnShaktool_Hurt, Shaktool_Hurt },
  { fnShaktool_Init, Shaktool_Init },
  { fnShaktool_Touch, Shaktool_Touch },
  { fnShaktool_Shot, Shaktool_Shot },
  { fnN00bTubeCracks_Init, N00bTubeCracks_Init },
  { fnChozoStatue_Init, ChozoStatue_Init },
  { fnChozoStatue_Main, ChozoStatue_Main },
  { fnnullsub_51, EnemyAi_Nop },
  { fnnullsub_52, EnemyAi_Nop },
  { fnWalkingSpacePirates_Powerbomb, WalkingSpacePirates_Powerbomb },
  { fnWalkingSpacePirates_Touch, WalkingSpacePirates_Touch },
  { fnWalkingSpacePirates_Shot, WalkingSpacePirates_Shot },
  { fnWalkingSpacePirates_87C8, WalkingSpacePirates_87C8 },
  { fnWalkingSpacePirates_883E, WalkingSpacePirates_883E },
  { fnWallSpacePirates_Init, WallSpacePirates_Init },
  { fnWallSpacePirates_Main, WallSpacePirates_Main },
  { fnNinjaSpacePirates_Init, NinjaSpacePirates_Init },
  { fnNinjaSpacePirates_Main, NinjaSpacePirates_Main },
  { fnWalkingSpacePirates_Init, WalkingSpacePirates_Init },
  { fnWalkingSpacePirates_Main, WalkingSpacePirates_Main },
  { fnUnusedSpinningTurtleEye_Init, UnusedSpinningTurtleEye_Init },
  { fnUnusedSpinningTurtleEye_Main, UnusedSpinningTurtleEye_Main },
  { fnBrinstarPipeBug_Init, BrinstarPipeBug_Init },
  { fnBrinstarPipeBug_Main, BrinstarPipeBug_Main },
  { fnNorfairPipeBug_Init, NorfairPipeBug_Init },
  { fnNorfairPipeBug_Main, NorfairPipeBug_Main },
  { fnBrinstarYellowPipeBug_Init, BrinstarYellowPipeBug_Init },
  { fnBrinstarYellowPipeBug_Main, BrinstarYellowPipeBug_Main },
  { fnBotwoon_Init, Botwoon_Init },
  { fnBotwoon_Main, Botwoon_Main },
  { fnBotwoon_Touch, Botwoon_Touch },
  { fnBotwoon_Shot, Botwoon_Shot },
  { fnBotwoon_Powerbomb, Botwoon_Powerbomb },
  { fnEscapeEtecoon_Main, EscapeEtecoon_Main },
  { fnEscapeEtecoon_Init, EscapeEtecoon_Init },
  { fnEscapeDachora_Init, EscapeDachora_Init },
  { fnnullsub_54, EnemyAi_Nop },
};

typedef struct EnemyPreInstrAddrMap {
  uint32 addr;
  EnemyPreInstrFn fn;
} EnemyPreInstrAddrMap;

static const EnemyPreInstrAddrMap kEnemyPreInstrByAddr[] = {
  { fnnullsub_171, EnemyPreInstr_Nop },
  { fnMiniCrocomire_PreInstr5, MiniCrocomire_PreInstr5 },
  { fnMiniCrocomire_PreInstr6, MiniCrocomire_PreInstr6 },
  { fnnullsub_175, EnemyPreInstr_Nop },
  { fnSpikeShootingPlant_2, SpikeShootingPlant_2 },
  { fnSpikeShootingPlant_3, SpikeShootingPlant_3 },
  { fnnullsub_182, EnemyPreInstr_Nop },
  { fnnullsub_187, EnemyPreInstr_Nop },
  { fnGunshipTop_3, GunshipTop_3 },
  { fnGunshipTop_4, GunshipTop_4 },
  { fnGunshipTop_5, GunshipTop_5 },
  { fnGunshipTop_6, GunshipTop_6 },
  { fnGunshipTop_7, GunshipTop_7 },
  { fnGunshipTop_8, GunshipTop_8 },
  { fnGunshipTop_9, GunshipTop_9 },
  { fnGunshipTop_10, GunshipTop_10 },
  { fnGunshipTop_11, GunshipTop_11 },
  { fnGunshipTop_12, GunshipTop_12 },
  { fnGunshipTop_13, GunshipTop_13 },
  { fnGunshipTop_14, GunshipTop_14 },
  { fnGunshipTop_15, GunshipTop_15 },
  { fnGunshipTop_16, GunshipTop_16 },
  { fnGunshipTop_17, GunshipTop_17 },
  { fnGunshipTop_18, GunshipTop_18 },
  { fnGunshipTop_19, GunshipTop_19 },
  { fnGunshipTop_20, GunshipTop_20 },
  { fnGunshipTop_21, GunshipTop_21 },
  { fnFlies_4, Flies_4 },
  { fnFlies_5, Flies_5 },
  { fnFlies_6, Flies_6 },
  { fnFlies_7, Flies_7 },
  { fnNorfairLavajumpingEnemy_Func_1, NorfairLavajumpingEnemy_Func_1 },
  { fnNorfairLavajumpingEnemy_Func_2, NorfairLavajumpingEnemy_Func_2 },
  { fnNorfairLavajumpingEnemy_Func_3, NorfairLavajumpingEnemy_Func_3 },
  { fnNorfairLavajumpingEnemy_Func_4, NorfairLavajumpingEnemy_Func_4 },
  { fnNorfairLavajumpingEnemy_Func_5, NorfairLavajumpingEnemy_Func_5 },
  { fnNorfairRio_Func_1, NorfairRio_Func_1 },
  { fnNorfairRio_Func_2, NorfairRio_Func_2 },
  { fnNorfairRio_Func_3, NorfairRio_Func_3 },
  { fnNorfairRio_Func_4, NorfairRio_Func_4 },
  { fnNorfairRio_Func_5, NorfairRio_Func_5 },
  { fnNorfairRio_Func_6, NorfairRio_Func_6 },
  { fnLowerNorfairRio_Func_1, LowerNorfairRio_Func_1 },
  { fnLowerNorfairRio_Func_2, LowerNorfairRio_Func_2 },
  { fnLowerNorfairRio_Func_3, LowerNorfairRio_Func_3 },
  { fnLowerNorfairRio_Func_4, LowerNorfairRio_Func_4 },
  { fnLowerNorfairRio_Func_5, LowerNorfairRio_Func_5 },
  { fnLowerNorfairRio_Func_6, LowerNorfairRio_Func_6 },
  { fnMaridiaLargeSnail_Func_7, MaridiaLargeSnail_Func_7 },
  { fnMaridiaLargeSnail_Func_8, MaridiaLargeSnail_Func_8 },
  { fnLavaSeahorse_Func_1, LavaSeahorse_Func_1 },
  { fnLavaSeahorse_Func_2, LavaSeahorse_Func_2 },
  { fnLavaSeahorse_Func_3, LavaSeahorse_Func_3 },
  { fnLavaSeahorse_Func_4, LavaSeahorse_Func_4 },
  { fnLavaSeahorse_Func_5, LavaSeahorse_Func_5 },
  { fnnullsub_196, EnemyPreInstr_Nop },
  { fnBang_Func_6, Bang_Func_6 },
  { fnBang_Func_7, Bang_Func_7 },
  { fnBang_Func_8, Bang_Func_8 },
  { fnBang_Func_10, Bang_Func_10 },
  { fnBang_Func_11, Bang_Func_11 },
  { fnnullsub_215, EnemyPreInstr_Nop },
  { fnMaridiaSnail_Func_7, MaridiaSnail_Func_7 },
  { fnMaridiaSnail_Func_9, MaridiaSnail_Func_9 },
  { fnMaridiaSnail_CFB7, MaridiaSnail_CFB7 },
  { fnMaridiaSnail_CFBD, MaridiaSnail_CFBD },
  { fnMaridiaSnail_CFCE, MaridiaSnail_CFCE },
  { fnMaridiaSnail_CFD4, MaridiaSnail_CFD4 },
  { fnMaridiaSnail_CFE5, MaridiaSnail_CFE5 },
  { fnMaridiaSnail_CFEB, MaridiaSnail_CFEB },
  { fnMaridiaSnail_CFFC, MaridiaSnail_CFFC },
  { fnMaridiaSnail_Func_15, MaridiaSnail_Func_15 },
  { fnnullsub_343, EnemyPreInstr_Nop },
  { fnWreckedShipOrangeZoomer_Func_2, WreckedShipOrangeZoomer_Func_2 },
  { fnsub_A3E168, sub_A3E168 },
  { fnnullsub_304, EnemyPreInstr_Nop },
  { fnFireZoomer_Func_1, FireZoomer_Func_1 },
  { fnFireZoomer_Func_2, FireZoomer_Func_2 },
  { fnFireZoomer_Func_3, FireZoomer_Func_3 },
  { fnnullsub_237, EnemyPreInstr_Nop },
  { fnPhantoon_Spawn8FireballsInCircleAtStart, Phantoon_Spawn8FireballsInCircleAtStart },
  { fnPhantoon_WaitBetweenSpawningAndSpinningFireballs, Phantoon_WaitBetweenSpawningAndSpinningFireballs },
  { fnPhantoon_SpawnFireballsBeforeFight, Phantoon_SpawnFireballsBeforeFight },
  { fnPhantoon_WavyFadeIn, Phantoon_WavyFadeIn },
  { fnPhantoon_PickPatternForRound1, Phantoon_PickPatternForRound1 },
  { fnPhantoon_MovePhantoonInFigure8ThenOpenEye, Phantoon_MovePhantoonInFigure8ThenOpenEye },
  { fnPhantoon_EyeFollowsSamusUntilTimerRunsOut, Phantoon_EyeFollowsSamusUntilTimerRunsOut },
  { fnPhantoon_BecomesSolidAndBodyVuln, Phantoon_BecomesSolidAndBodyVuln },
  { fnPhantoon_IsSwooping, Phantoon_IsSwooping },
  { fnPhantoon_FadeoutWithSwoop, Phantoon_FadeoutWithSwoop },
  { fnPhantoon_WaitAfterFadeOut, Phantoon_WaitAfterFadeOut },
  { fnPhantoon_MoveLeftOrRightAndPickEyeOpenPatt, Phantoon_MoveLeftOrRightAndPickEyeOpenPatt },
  { fnPhantoon_FadeInBeforeFigure8, Phantoon_FadeInBeforeFigure8 },
  { fnPhantoon_BecomeSolidAfterRainingFireballs, Phantoon_BecomeSolidAfterRainingFireballs },
  { fnPhantoon_FadeInDuringFireballRain, Phantoon_FadeInDuringFireballRain },
  { fnPhantoon_FollowSamusWithEyeDuringFireballRain, Phantoon_FollowSamusWithEyeDuringFireballRain },
  { fnPhantoon_FadeOutDuringFireballRain, Phantoon_FadeOutDuringFireballRain },
  { fnPhantoon_SpawnRainingFireballs, Phantoon_SpawnRainingFireballs },
  { fnPhantoon_FadeOutBeforeFirstFireballRain, Phantoon_FadeOutBeforeFirstFireballRain },
  { fnPhantoon_FadeOutBeforeEnrage, Phantoon_FadeOutBeforeEnrage },
  { fnPhantoon_MoveEnragedPhantoonToTopCenter, Phantoon_MoveEnragedPhantoonToTopCenter },
  { fnPhantoon_FadeInEnragedPhantoon, Phantoon_FadeInEnragedPhantoon },
  { fnPhantoon_Enraged, Phantoon_Enraged },
  { fnPhantoon_FadeoutAfterEnrage, Phantoon_FadeoutAfterEnrage },
  { fnPhantoon_CompleteSwoopAfterFatalShot, Phantoon_CompleteSwoopAfterFatalShot },
  { fnPhantoon_DyingPhantoonFadeInOut, Phantoon_DyingPhantoonFadeInOut },
  { fnPhantoon_DyingPhantoonExplosions, Phantoon_DyingPhantoonExplosions },
  { fnPhantoon_WavyDyingPhantoonAndCry, Phantoon_WavyDyingPhantoonAndCry },
  { fnPhantoon_DyingFadeOut, Phantoon_DyingFadeOut },
  { fnPhantoon_AlmostDead, Phantoon_AlmostDead },
  { fnPhantoon_Dead, Phantoon_Dead },
  { fnEtecoon_Func_4, Etecoon_Func_4 },
  { fnEtecoon_Func_5, Etecoon_Func_5 },
  { fnEtecoon_Func_6, Etecoon_Func_6 },
  { fnEtecoon_Func_7, Etecoon_Func_7 },
  { fnEtecoon_Func_8, Etecoon_Func_8 },
  { fnEtecoon_Func_9, Etecoon_Func_9 },
  { fnEtecoon_Func_10, Etecoon_Func_10 },
  { fnEtecoon_Func_11, Etecoon_Func_11 },
  { fnEtecoon_Func_12, Etecoon_Func_12 },
  { fnEtecoon_Func_16, Etecoon_Func_16 },
  { fnEtecoon_Func_17, Etecoon_Func_17 },
  { fnEtecoon_Func_18, Etecoon_Func_18 },
  { fnEtecoon_Func_19, Etecoon_Func_19 },
  { fnEtecoon_Func_20, Etecoon_Func_20 },
  { fnEtecoon_Func_21, Etecoon_Func_21 },
  { fnEtecoon_Func_22, Etecoon_Func_22 },
  { fnEtecoon_Func_23, Etecoon_Func_23 },
  { fnEtecoon_Func_24, Etecoon_Func_24 },
  { fnEtecoon_Func_25, Etecoon_Func_25 },
  { fnEtecoon_Func_26, Etecoon_Func_26 },
  { fnDachora_Func_2, Dachora_Func_2 },
  { fnDachora_Func_3, Dachora_Func_3 },
  { fnDachora_Func_4, Dachora_Func_4 },
  { fnDachora_Func_5, Dachora_Func_5 },
  { fnDachora_Func_7, Dachora_Func_7 },
  { fnDachora_Func_8, Dachora_Func_8 },
  { fnDachora_Func_11, Dachora_Func_11 },
  { fnDachora_Func_12, Dachora_Func_12 },
  { fnMorphBallEye_Func_1, MorphBallEye_Func_1 },
  { fnMorphBallEye_Func_2, MorphBallEye_Func_2 },
  { fnMorphBallEye_Func_3, MorphBallEye_Func_3 },
  { fnMorphBallEye_Func_4, MorphBallEye_Func_4 },
  { fnnullsub_244, EnemyPreInstr_Nop },
  { fnNorfairLavaMan_Func_7, NorfairLavaMan_Func_7 },
  { fnNorfairLavaMan_Func_8, NorfairLavaMan_Func_8 },
  { fnsub_A8B193, sub_A8B193 },
  { fnNorfairLavaMan_Func_9, NorfairLavaMan_Func_9 },
  { fnNorfairLavaMan_Func_10, NorfairLavaMan_Func_10 },
  { fnNorfairLavaMan_Func_11, NorfairLavaMan_Func_11 },
  { fnsub_A8B291, sub_A8B291 },
  { fnNorfairLavaMan_Func_13, pre_thunk_NorfairLavaMan_Func_13 },
  { fnNorfairLavaMan_Func_15, NorfairLavaMan_Func_15 },
  { fnNorfairLavaMan_Func_16, NorfairLavaMan_Func_16 },
  { fnNorfairLavaMan_Func_17, NorfairLavaMan_Func_17 },
  { fnNorfairLavaMan_Func_18, NorfairLavaMan_Func_18 },
  { fnMaridiaFloater_Func_3, MaridiaFloater_Func_3 },
  { fnMaridiaFloater_Func_4, MaridiaFloater_Func_4 },
  { fnMaridiaFloater_Func_5, MaridiaFloater_Func_5 },
  { fnMaridiaFloater_Func_6, MaridiaFloater_Func_6 },
  { fnMaridiaFloater_Func_7, MaridiaFloater_Func_7 },
  { fnMaridiaFloater_Func_8, MaridiaFloater_Func_8 },
  { fnMaridiaFloater_Func_9, MaridiaFloater_Func_9 },
  { fnMaridiaFloater_Func_10, MaridiaFloater_Func_10 },
  { fnMaridiaFloater_Func_11, MaridiaFloater_Func_11 },
  { fnnullsub_256, EnemyPreInstr_Nop },
  { fnMaridiaFloater_Func_12, MaridiaFloater_Func_12 },
  { fnMaridiaFloater_Func_13, MaridiaFloater_Func_13 },
  { fnTorizo_Func_5, Torizo_Func_5 },
  { fnTorizo_Func_6, Torizo_Func_6 },
  { fnTorizo_Func_7, Torizo_Func_7 },
  { fnnullsub_344, EnemyPreInstr_Nop },
  { fnTorizo_D5ED, Torizo_D5ED },
  { fnTorizo_D5F1, Torizo_D5F1 },
  { fnnullsub_274, EnemyPreInstr_Nop },
  { fnnullsub_275, EnemyPreInstr_Nop },
  { fnShaktool_DCAC, Shaktool_DCAC },
  { fnShaktool_DCD7, Shaktool_DCD7 },
  { fnShaktool_DD25, Shaktool_DD25 },
  { fnsub_AAE445, sub_AAE445 },
  { fnnullsub_276, EnemyPreInstr_Nop },
  { fnShaktool_PreInstr_0, Shaktool_PreInstr_0 },
  { fnnullsub_277, EnemyPreInstr_Nop },
  { fnBrinstarPipeBug_PreInstr_1, BrinstarPipeBug_PreInstr_1 },
  { fnBrinstarPipeBug_PreInstr_2, BrinstarPipeBug_PreInstr_2 },
  { fnBrinstarPipeBug_PreInstr_3, BrinstarPipeBug_PreInstr_3 },
  { fnBrinstarPipeBug_PreInstr_4, BrinstarPipeBug_PreInstr_4 },
  { fnBrinstarPipeBug_PreInstr_5, BrinstarPipeBug_PreInstr_5 },
  { fnNorfairPipeBug_Func_5, NorfairPipeBug_Func_5 },
  { fnBotwoon_Func_26, Botwoon_Func_26 },
  { fnBotwoon_Func_27, Botwoon_Func_27 },
  { fnBotwoon_Func_28, Botwoon_Func_28 },
  { fnBotwoon_Func_29, Botwoon_Func_29 },
  { fnBotwoon_Func_30, Botwoon_Func_30 },
  { fnEscapeEtecoon_E65C, EscapeEtecoon_E65C },
  { fnEscapeEtecoon_E670, EscapeEtecoon_E670 },
  { fnEscapeEtecoon_E680, EscapeEtecoon_E680 },
};

typedef struct EnemyInstrAddrMap {
  uint32 addr;
  EnemyInstrFn fn;
} EnemyInstrAddrMap;

static const EnemyInstrAddrMap kEnemyInstrByAddr[] = {
  { 0xA0806B, EnemyInstr_SetAiPreInstr },
  { 0xA08074, EnemyInstr_ClearAiPreInstr },
  { fnEnemyInstr_StopScript, EnemyInstr_StopScript },
  { fnEnemyInstr_Goto, EnemyInstr_Goto },
  { fnEnemyInstr_DecTimerAndGoto, EnemyInstr_DecTimerAndGoto },
  { fnEnemyInstr_DecTimerAndGoto2, EnemyInstr_DecTimerAndGoto },
  { fnEnemyInstr_SetTimer, EnemyInstr_SetTimer },
  { fnEnemyInstr_Sleep, EnemyInstr_Sleep },
  { fnEnemyInstr_WaitNframes, EnemyInstr_WaitNframes },
  { fnEnemyInstr_CopyToVram, EnemyInstr_CopyToVram },
  { fnEnemyInstr_EnableOffScreenProcessing, EnemyInstr_EnableOffScreenProcessing },
  { fnEnemyInstr_DisableOffScreenProcessing, EnemyInstr_DisableOffScreenProcessing },
  { fnBouncingGoofball_Instr_88C5, BouncingGoofball_Instr_88C5 },
  { fnBouncingGoofball_Instr_88C6, BouncingGoofball_Instr_88C6 },
  { fnMiniCrocomire_Instr_897E, MiniCrocomire_Instr_897E },
  { fnMiniCrocomire_Instr_8990, MiniCrocomire_Instr_8990 },
  { fnMiniCrocomire_Instr_899D, MiniCrocomire_Instr_899D },
  { fnMaridiaBeybladeTurtle_Instr_9381, MaridiaBeybladeTurtle_Instr_9381 },
  { fnMaridiaBeybladeTurtle_Instr_9412, MaridiaBeybladeTurtle_Instr_9412 },
  { fnMaridiaBeybladeTurtle_Instr_9447, MaridiaBeybladeTurtle_Instr_9447 },
  { fnMaridiaBeybladeTurtle_Instr_9451, MaridiaBeybladeTurtle_Instr_9451 },
  { fnMaridiaBeybladeTurtle_Instr_946B, MaridiaBeybladeTurtle_Instr_946B },
  { fnMaridiaBeybladeTurtle_Instr_9485, MaridiaBeybladeTurtle_Instr_9485 },
  { fnMaridiaBeybladeTurtle_Instr_94A1, MaridiaBeybladeTurtle_Instr_94A1 },
  { fnMaridiaBeybladeTurtle_Instr_94C7, MaridiaBeybladeTurtle_Instr_94C7 },
  { fnMaridiaBeybladeTurtle_Instr_94D1, MaridiaBeybladeTurtle_Instr_94D1 },
  { fnSpikeShootingPlant_Instr_9F2A, SpikeShootingPlant_Instr_9F2A },
  { fnSpikeShootingPlant_Instr_A095, SpikeShootingPlant_Instr_A095 },
  { fnSpikeShootingPlant_Instr_A0A7, SpikeShootingPlant_Instr_A0A7 },
  { fnMaridiaSpikeyShell_Instr_A56D, MaridiaSpikeyShell_Instr_A56D },
  { fnMaridiaSpikeyShell_Instr_A571, MaridiaSpikeyShell_Instr_A571 },
  { fnRinka_Instr_B9B3, Rinka_Instr_B9B3 },
  { fnRinka_Instr_B9BD, Rinka_Instr_B9BD },
  { fnRinka_Instr_B9C7, Rinka_Instr_B9C7 },
  { fnEnemyInstr_Rio_Instr_1, EnemyInstr_Rio_Instr_1 },
  { fnNorfairLavajumpingEnemy_Instr_BE8E, NorfairLavajumpingEnemy_Instr_BE8E },
  { fnNorfairRio_Instr_C1C9, NorfairRio_Instr_C1C9 },
  { fnNorfairRio_Instr_C1D4, NorfairRio_Instr_C1D4 },
  { fnNorfairRio_Instr_C1DF, NorfairRio_Instr_C1DF },
  { fnNorfairRio_Instr_C1EA, NorfairRio_Instr_C1EA },
  { fnNorfairRio_Instr_C1F5, NorfairRio_Instr_C1F5 },
  { fnNorfairRio_Instr_C200, NorfairRio_Instr_C200 },
  { fnNorfairRio_Instr_C20B, NorfairRio_Instr_C20B },
  { fnNorfairRio_Instr_C216, NorfairRio_Instr_C216 },
  { fnNorfairRio_Instr_C221, NorfairRio_Instr_C221 },
  { fnNorfairRio_Instr_C22C, NorfairRio_Instr_C22C },
  { fnNorfairRio_Instr_C237, NorfairRio_Instr_C237 },
  { fnLowerNorfairRio_Instr_C6D2, LowerNorfairRio_Instr_C6D2 },
  { fnLowerNorfairRio_Instr_C6DD, LowerNorfairRio_Instr_C6DD },
  { fnLowerNorfairRio_Instr_C6E8, LowerNorfairRio_Instr_C6E8 },
  { fnMaridiaLargeSnail_Instr_CB6B, MaridiaLargeSnail_Instr_CB6B },
  { fnMaridiaLargeSnail_Instr_CCB3, MaridiaLargeSnail_Instr_CCB3 },
  { fnMaridiaLargeSnail_Instr_CCBE, MaridiaLargeSnail_Instr_CCBE },
  { fnMaridiaLargeSnail_Instr_CCC9, MaridiaLargeSnail_Instr_CCC9 },
  { fnLavaSeahorse_Instr_E5FB, LavaSeahorse_Instr_E5FB },
  { fnWaver_Instr_1, Waver_Instr_1 },
  { fnMetalee_Instr_1, Metalee_Instr_1 },
  { fnMaridiaFish_Instr_3, MaridiaFish_Instr_3 },
  { fnMaridiaFish_Instr_1, MaridiaFish_Instr_1 },
  { fnMaridiaFish_Instr_2, MaridiaFish_Instr_2 },
  { fnPlatformThatFallsWithSamus_Instr_3, PlatformThatFallsWithSamus_Instr_3 },
  { fnPlatformThatFallsWithSamus_Instr_4, PlatformThatFallsWithSamus_Instr_4 },
  { fnPlatformThatFallsWithSamus_Instr_1, PlatformThatFallsWithSamus_Instr_1 },
  { fnPlatformThatFallsWithSamus_Instr_2, PlatformThatFallsWithSamus_Instr_2 },
  { fnSidehopper_Func_1, Sidehopper_Func_1 },
  { fnSidehopper_Instr_1, Sidehopper_Instr_1 },
  { fnMaridiaRefillCandy_Instr_1, MaridiaRefillCandy_Instr_1 },
  { fnMaridiaRefillCandy_Instr_2, MaridiaRefillCandy_Instr_2 },
  { fnMaridiaRefillCandy_Instr_3, MaridiaRefillCandy_Instr_3 },
  { fnBang_Instr_1, Bang_Instr_1 },
  { fnBang_Instr_2, Bang_Instr_2 },
  { fnSkree_Instr_1, Skree_Instr_1 },
  { fnMaridiaSnail_Instr_1, MaridiaSnail_Instr_1 },
  { fnMaridiaSnail_Instr_2, MaridiaSnail_Instr_2 },
  { fnMaridiaSnail_Instr_4, MaridiaSnail_Instr_4 },
  { fnMaridiaSnail_Instr_3, MaridiaSnail_Instr_3 },
  { fnMaridiaSnail_Instr_5, MaridiaSnail_Instr_5 },
  { fnReflec_Instr_1, Reflec_Instr_1 },
  { fnWreckedShipOrangeZoomer_Func_1, WreckedShipOrangeZoomer_Func_1 },
  { fnZoomer_Instr_SetPreinstr, Zoomer_Instr_SetPreinstr },
  { fnMetroid_Instr_2, Metroid_Instr_2 },
  { fnMetroid_Instr_1, Metroid_Instr_1 },
  { fnCrocomire_Instr_1, Crocomire_Instr_1 },
  { fnCrocomire_Instr_14, Crocomire_Instr_14 },
  { fnCrocomire_Instr_11, Crocomire_Instr_11 },
  { fnCrocomire_Instr_7, Crocomire_Instr_7 },
  { fnCrocomire_Instr_19, Crocomire_Instr_19 },
  { fnCrocomire_Instr_2, Crocomire_Instr_2 },
  { fnCrocomire_Instr_4, Crocomire_Instr_4 },
  { fnCrocomire_Instr_3, Crocomire_Instr_3 },
  { fnCrocomire_Instr_15, Crocomire_Instr_15 },
  { fnCrocomire_Instr_16, Crocomire_Instr_16 },
  { fnCrocomire_Instr_13, Crocomire_Instr_13 },
  { fnCrocomire_Instr_18, Crocomire_Instr_18 },
  { fnCrocomire_Instr_12, Crocomire_Instr_12 },
  { fnCrocomire_Instr_17, Crocomire_Instr_17 },
  { fnCrocomire_Instr_8, Crocomire_Instr_8 },
  { fnCrocomire_Instr_6, Crocomire_Instr_6 },
  { fnCrocomire_Instr_9, Crocomire_Instr_9 },
  { fnCrocomire_Instr_5, Crocomire_Instr_5 },
  { fnCrocomire_Instr_20, Crocomire_Instr_20 },
  { fnCrocomire_Instr_21, Crocomire_Instr_21 },
  { fnCrocomire_Instr_22, Crocomire_Instr_22 },
  { fnCrocomire_Instr_23, Crocomire_Instr_23 },
  { fnCrocomire_Instr_24, Crocomire_Instr_24 },
  { fnCrocomire_Instr_10, Crocomire_Instr_10 },
  { fnCrocomire_Instr_25, Crocomire_Instr_25 },
  { fnCrocomire_Instr_26, Crocomire_Instr_26 },
  { fnCrocomire_Instr_27, Crocomire_Instr_27 },
  { fnDraygon_Instr_1, Draygon_Instr_1 },
  { fnDraygon_Instr_13, Draygon_Instr_13 },
  { fnDraygon_Instr_8, Draygon_Instr_8 },
  { fnDraygon_Instr_7, Draygon_Instr_7 },
  { fnDraygon_Instr_6, Draygon_Instr_6 },
  { fnDraygon_Instr_9, Draygon_Instr_9 },
  { fnDraygon_Instr_2, Draygon_Instr_2 },
  { fnDraygon_Instr_11, Draygon_Instr_11 },
  { fnDraygon_Instr_5, Draygon_Instr_5 },
  { fnDraygon_Instr_15, Draygon_Instr_15 },
  { fnDraygon_Instr_17, Draygon_Instr_17 },
  { fnDraygon_Instr_14, Draygon_Instr_14 },
  { fnDraygon_Instr_16, Draygon_Instr_16 },
  { fnDraygon_Instr_10, Draygon_Instr_10 },
  { fnDraygon_Instr_4, Draygon_Instr_4 },
  { fnDraygon_Instr_12, Draygon_Instr_12 },
  { fnDraygon_Instr_18, Draygon_Instr_18 },
  { fnDraygon_Instr_3, Draygon_Instr_3 },
  { fnDraygon_Instr_25, Draygon_Instr_25 },
  { fnDraygon_Instr_24, Draygon_Instr_24 },
  { fnDraygon_Instr_21, Draygon_Instr_21 },
  { fnDraygon_Instr_22, Draygon_Instr_22 },
  { fnDraygon_Instr_27, Draygon_Instr_27 },
  { fnDraygon_Instr_23, Draygon_Instr_23 },
  { fnDraygon_Instr_30, Draygon_Instr_30 },
  { fnDraygon_Instr_20, Draygon_Instr_20 },
  { fnDraygon_Instr_29, Draygon_Instr_29 },
  { fnDraygon_Instr_19, Draygon_Instr_19 },
  { fnDraygon_Instr_28, Draygon_Instr_28 },
  { fnDraygon_Instr_26, Draygon_Instr_26 },
  { fnFireGeyser_Instr_1, FireGeyser_Instr_1 },
  { fnFireGeyser_Instr_2, FireGeyser_Instr_2 },
  { fnFireGeyser_Instr_3, FireGeyser_Instr_3 },
  { fnFireGeyser_Instr_4, FireGeyser_Instr_4 },
  { fnFireGeyser_Instr_5, FireGeyser_Instr_5 },
  { fnFireGeyser_Instr_6, FireGeyser_Instr_6 },
  { fnFireGeyser_Instr_7, FireGeyser_Instr_7 },
  { fnFireGeyser_Instr_8, FireGeyser_Instr_8 },
  { fnFireGeyser_Instr_9, FireGeyser_Instr_9 },
  { fnFireGeyser_Instr_10, FireGeyser_Instr_10 },
  { fnFireGeyser_Instr_11, FireGeyser_Instr_11 },
  { fnFireGeyser_Instr_12, FireGeyser_Instr_12 },
  { fnFireGeyser_Instr_13, FireGeyser_Instr_13 },
  { fnFireGeyser_Instr_14, FireGeyser_Instr_14 },
  { fnFireGeyser_Instr_15, FireGeyser_Instr_15 },
  { fnFireGeyser_Instr_16, FireGeyser_Instr_16 },
  { fnFireGeyser_Instr_17, FireGeyser_Instr_17 },
  { fnFireGeyser_Instr_18, FireGeyser_Instr_18 },
  { fnFireGeyser_Instr_19, FireGeyser_Instr_19 },
  { fnFireGeyser_Instr_20, FireGeyser_Instr_20 },
  { fnFireGeyser_Instr_21, FireGeyser_Instr_21 },
  { fnFireGeyser_Instr_22, FireGeyser_Instr_22 },
  { fnFireGeyser_Instr_23, FireGeyser_Instr_23 },
  { fnFireGeyser_Instr_24, FireGeyser_Instr_24 },
  { fnFakeKraid_Instr_2, FakeKraid_Instr_2 },
  { fnFakeKraid_Instr_1, FakeKraid_Instr_1 },
  { fnFakeKraid_Instr_3, FakeKraid_Instr_3 },
  { fnFakeKraid_Instr_4, FakeKraid_Instr_4 },
  { fnFakeKraid_Instr_5, FakeKraid_Instr_5 },
  { fnRidley_Instr_5, Ridley_Instr_5 },
  { fnRidley_Instr_6, Ridley_Instr_6 },
  { fnRidley_Instr_10, Ridley_Instr_10 },
  { fnRidley_Instr_4, Ridley_Instr_4 },
  { fnRidley_Instr_3, Ridley_Instr_3 },
  { fnRidley_Instr_2, Ridley_Instr_2 },
  { fnRidley_Instr_1, Ridley_Instr_1 },
  { fnRidley_Instr_14, Ridley_Instr_14 },
  { fnRidley_Instr_9, Ridley_Instr_9 },
  { fnRidley_Instr_7, Ridley_Instr_7 },
  { fnRidley_Instr_8, Ridley_Instr_8 },
  { fnRidley_Instr_11, Ridley_Instr_11 },
  { fnRidley_Instr_12, Ridley_Instr_12 },
  { fnRidley_Instr_13, Ridley_Instr_13 },
  { fnRidley_Instr_15, Ridley_Instr_15 },
  { fnRidley_Instr_16, Ridley_Instr_16 },
  { fnCeresSteam_Instr_1, CeresSteam_Instr_1 },
  { fnCeresSteam_Instr_2, CeresSteam_Instr_2 },
  { fnCeresSteam_Instr_3, CeresSteam_Instr_3 },
  { fnCeresDoor_Instr_6, CeresDoor_Instr_6 },
  { fnCeresDoor_Instr_4, CeresDoor_Instr_4 },
  { fnCeresDoor_Instr_8, CeresDoor_Instr_8 },
  { fnCeresSteam_Instr_4, CeresSteam_Instr_4 },
  { fnCeresDoor_Instr_1, CeresDoor_Instr_1 },
  { fnCeresDoor_Instr_3, CeresDoor_Instr_3 },
  { fnCeresSteam_Instr_5, CeresSteam_Instr_5 },
  { fnCeresDoor_Instr_5, CeresDoor_Instr_5 },
  { fnCeresDoor_Instr_2, CeresDoor_Instr_2 },
  { fnCeresDoor_Instr_7, CeresDoor_Instr_7 },
  { fnEnemyInstr_Call_A7, EnemyInstr_Call_A7 },
  { fnKraid_Instr_9, Kraid_Instr_9 },
  { fnKraid_Instr_1, Kraid_Instr_1 },
  { fnKraid_Instr_DecYpos, Kraid_Instr_DecYpos },
  { fnKraid_Instr_IncrYpos_Shake, Kraid_Instr_IncrYpos_Shake },
  { fnKraid_Instr_PlaySound_0x76, Kraid_Instr_PlaySound_0x76 },
  { fnKraid_Instr_XposMinus3, Kraid_Instr_XposMinus3 },
  { fnKraid_Instr_XposMinus3b, Kraid_Instr_XposMinus3b },
  { fnKraid_Instr_XposPlus3, Kraid_Instr_XposPlus3 },
  { fnKraid_Instr_MoveHimRight, Kraid_Instr_MoveHimRight },
  { fnMiniDraygon_Instr_2, MiniDraygon_Instr_2 },
  { fnMiniDraygon_Instr_1, MiniDraygon_Instr_1 },
  { fnMiniDraygon_Instr_3, MiniDraygon_Instr_3 },
  { fnMiniDraygon_Instr_4, MiniDraygon_Instr_4 },
  { fnFune_Instr_2, Fune_Instr_2 },
  { fnFune_Instr_6, Fune_Instr_6 },
  { fnFune_Instr_7, Fune_Instr_7 },
  { fnFune_Instr_1, Fune_Instr_1 },
  { fnFune_Instr_4, Fune_Instr_4 },
  { fnFune_Instr_3, Fune_Instr_3 },
  { fnFune_Instr_5, Fune_Instr_5 },
  { fnYappingMaw_Instr_2, YappingMaw_Instr_2 },
  { fnYappingMaw_Instr_4, YappingMaw_Instr_4 },
  { fnYappingMaw_Instr_5, YappingMaw_Instr_5 },
  { fnYappingMaw_Instr_7, YappingMaw_Instr_7 },
  { fnYappingMaw_Instr_3, YappingMaw_Instr_3 },
  { fnYappingMaw_Instr_6, YappingMaw_Instr_6 },
  { fnYappingMaw_Instr_1, YappingMaw_Instr_1 },
  { fnNorfairLavaMan_Instr_1, NorfairLavaMan_Instr_1 },
  { fnNorfairLavaMan_Instr_8, NorfairLavaMan_Instr_8 },
  { fnNorfairLavaMan_Instr_14, NorfairLavaMan_Instr_14 },
  { fnNorfairLavaMan_Instr_2, NorfairLavaMan_Instr_2 },
  { fnNorfairLavaMan_Instr_7, NorfairLavaMan_Instr_7 },
  { fnNorfairLavaMan_Instr_10, NorfairLavaMan_Instr_10 },
  { fnNorfairLavaMan_Instr_12, NorfairLavaMan_Instr_12 },
  { fnNorfairLavaMan_Instr_9, NorfairLavaMan_Instr_9 },
  { fnNorfairLavaMan_Instr_11, NorfairLavaMan_Instr_11 },
  { fnNorfairLavaMan_Instr_13, NorfairLavaMan_Instr_13 },
  { fnNorfairLavaMan_Instr_5, NorfairLavaMan_Instr_5 },
  { fnNorfairLavaMan_Instr_15, NorfairLavaMan_Instr_15 },
  { fnNorfairLavaMan_Instr_4, NorfairLavaMan_Instr_4 },
  { fnNorfairLavaMan_Instr_16, NorfairLavaMan_Instr_16 },
  { fnNorfairLavaMan_Instr_6, NorfairLavaMan_Instr_6 },
  { fnNorfairLavaMan_Instr_3, NorfairLavaMan_Instr_3 },
  { fnBeetom_Instr_1, Beetom_Instr_1 },
  { fnWreckedShipRobot_Instr_4, WreckedShipRobot_Instr_4 },
  { fnWreckedShipRobot_Instr_9, WreckedShipRobot_Instr_9 },
  { fnWreckedShipRobot_Instr_6, WreckedShipRobot_Instr_6 },
  { fnWreckedShipRobot_Instr_8, WreckedShipRobot_Instr_8 },
  { fnWreckedShipRobot_Instr_7, WreckedShipRobot_Instr_7 },
  { fnWreckedShipRobot_Instr_15, WreckedShipRobot_Instr_15 },
  { fnWreckedShipRobot_Instr_18, WreckedShipRobot_Instr_18 },
  { fnWreckedShipRobot_Instr_16, WreckedShipRobot_Instr_16 },
  { fnWreckedShipRobot_Instr_17, WreckedShipRobot_Instr_17 },
  { fnWreckedShipRobot_Instr_3, WreckedShipRobot_Instr_3 },
  { fnWreckedShipRobot_Instr_10, WreckedShipRobot_Instr_10 },
  { fnWreckedShipRobot_Instr_14, WreckedShipRobot_Instr_14 },
  { fnWreckedShipRobot_Instr_2, WreckedShipRobot_Instr_2 },
  { fnWreckedShipRobot_Instr_13, WreckedShipRobot_Instr_13 },
  { fnWreckedShipRobot_Instr_1, WreckedShipRobot_Instr_1 },
  { fnWreckedShipRobot_Instr_12, WreckedShipRobot_Instr_12 },
  { fnWreckedShipRobot_Instr_5, WreckedShipRobot_Instr_5 },
  { fnWreckedShipRobot_Instr_11, WreckedShipRobot_Instr_11 },
  { fnWalkingLavaSeahorse_Instr_4, WalkingLavaSeahorse_Instr_4 },
  { fnWalkingLavaSeahorse_Instr_3, WalkingLavaSeahorse_Instr_3 },
  { fnWalkingLavaSeahorse_Instr_5, WalkingLavaSeahorse_Instr_5 },
  { fnWalkingLavaSeahorse_Instr_6, WalkingLavaSeahorse_Instr_6 },
  { fnWalkingLavaSeahorse_Instr_2, WalkingLavaSeahorse_Instr_2 },
  { fnWalkingLavaSeahorse_Instr_1, WalkingLavaSeahorse_Instr_1 },
  { fnWreckedShipSpark_Instr_2, WreckedShipSpark_Instr_2 },
  { fnWreckedShipSpark_Instr_1, WreckedShipSpark_Instr_1 },
  { fnKiHunter_Instr_1, KiHunter_Instr_1 },
  { fnKiHunter_Instr_2, KiHunter_Instr_2 },
  { fnKiHunter_Instr_3, KiHunter_Instr_3 },
  { fnKiHunter_Instr_4, KiHunter_Instr_4 },
  { fnKiHunter_Instr_5, KiHunter_Instr_5 },
  { fnMotherBrain_Instr_MoveBodyUp10Left4, MotherBrain_Instr_MoveBodyUp10Left4 },
  { fnMotherBrain_Instr_MoveBodyUp16Left4, MotherBrain_Instr_MoveBodyUp16Left4 },
  { fnMotherBrain_Instr_MoveBodyUp12Right2, MotherBrain_Instr_MoveBodyUp12Right2 },
  { fnMotherBrain_Instr_MoveDown12Left4, MotherBrain_Instr_MoveDown12Left4 },
  { fnMotherBrain_Instr_MoveDown16Right2, MotherBrain_Instr_MoveDown16Right2 },
  { fnMotherBrain_Instr_MoveDown10Right2, MotherBrain_Instr_MoveDown10Right2 },
  { fnMotherBrain_Instr_MoveUp2Right1, MotherBrain_Instr_MoveUp2Right1 },
  { fnMotherBrain_Instr_MoveRight2, MotherBrain_Instr_MoveRight2 },
  { fnMotherBrain_Instr_MoveUp1, MotherBrain_Instr_MoveUp1 },
  { fnMotherBrain_Instr_MoveUp1Right3_Sfx, MotherBrain_Instr_MoveUp1Right3_Sfx },
  { fnMotherBrain_Instr_Down2Right15, MotherBrain_Instr_Down2Right15 },
  { fnMotherBrain_Instr_Down4Right6, MotherBrain_Instr_Down4Right6 },
  { fnMotherBrain_Instr_Up4Left2, MotherBrain_Instr_Up4Left2 },
  { fnMotherBrain_Instr_Up2Left1_Sfx, MotherBrain_Instr_Up2Left1_Sfx },
  { fnMotherBrain_Instr_Up2Left1_Sfx2, MotherBrain_Instr_Up2Left1_Sfx2 },
  { fnMotherBrain_Instr_MoveLeft2, MotherBrain_Instr_MoveLeft2 },
  { fnMotherBrain_Instr_MoveDown1, MotherBrain_Instr_MoveDown1 },
  { fnMotherBrain_Instr_MoveDown1Left3, MotherBrain_Instr_MoveDown1Left3 },
  { fnMotherBrain_Instr_MoveUp2Left15_Sfx, MotherBrain_Instr_MoveUp2Left15_Sfx },
  { fnMotherBrain_Instr_MoveUp4Left6, MotherBrain_Instr_MoveUp4Left6 },
  { fnMotherBrain_Instr_MoveDown4Right2, MotherBrain_Instr_MoveDown4Right2 },
  { fnMotherBrain_Instr_MoveDown2Right1, MotherBrain_Instr_MoveDown2Right1 },
  { fnMotherBrain_Instr_SetPose_Standing, MotherBrain_Instr_SetPose_Standing },
  { fnMotherBrain_Instr_SetPose_Walking, MotherBrain_Instr_SetPose_Walking },
  { fnMotherBrain_Instr_SetPose_Crouched, MotherBrain_Instr_SetPose_Crouched },
  { fnMotherBrain_Instr_SetPose_CrouchedTrans, MotherBrain_Instr_SetPose_CrouchedTrans },
  { fnMotherBrain_Instr_SetPose_DeathBeamMode, MotherBrain_Instr_SetPose_DeathBeamMode },
  { fnMotherBrain_Instr_SetPose_LeaningDown, MotherBrain_Instr_SetPose_LeaningDown },
  { fnMotherBrain_Instr_SpawnEprojToOffset, MotherBrain_Instr_SpawnEprojToOffset },
  { fnMotherBrain_Instr_SpawnDeathBeamEproj, MotherBrain_Instr_SpawnDeathBeamEproj },
  { fnMotherBrain_Instr_IncrBeamAttackPhase, MotherBrain_Instr_IncrBeamAttackPhase },
  { fnShitroid_Instr_1, Shitroid_Instr_1 },
  { fnShitroid_Instr_2, Shitroid_Instr_2 },
  { fnsub_A9ECD0, sub_A9ECD0 },
  { fnShitroid_Instr_3, Shitroid_Instr_3 },
  { fnShitroid_Instr_4, Shitroid_Instr_4 },
  { fnShitroid_Instr_6, Shitroid_Instr_6 },
  { fnShitroid_Instr_5, Shitroid_Instr_5 },
  { fnTorizo_Instr_3, Torizo_Instr_3 },
  { fnTorizo_Instr_31, Torizo_Instr_31 },
  { fnTorizo_Instr_33, Torizo_Instr_33 },
  { fnTorizo_Instr_36, Torizo_Instr_36 },
  { fnTorizo_Instr_37, Torizo_Instr_37 },
  { fnTorizo_Instr_35, Torizo_Instr_35 },
  { fnTorizo_Instr_38, Torizo_Instr_38 },
  { fnTorizo_Instr_6, Torizo_Instr_6 },
  { fnTorizo_Instr_5, Torizo_Instr_5 },
  { fnTorizo_Instr_9, Torizo_Instr_9 },
  { fnTorizo_Instr_7, Torizo_Instr_7 },
  { fnTorizo_Instr_2, Torizo_Instr_2 },
  { fnTorizo_Instr_8, Torizo_Instr_8 },
  { fnTorizo_Instr_25, Torizo_Instr_25 },
  { fnTorizo_Instr_22, Torizo_Instr_22 },
  { fnTorizo_Instr_19, Torizo_Instr_19 },
  { fnTorizo_Instr_32, Torizo_Instr_32 },
  { fnTorizo_Instr_30, Torizo_Instr_30 },
  { fnTorizo_Instr_34, Torizo_Instr_34 },
  { fnTorizo_Instr_24, Torizo_Instr_24 },
  { fnTorizo_Instr_12, Torizo_Instr_12 },
  { fnTorizo_Instr_10, Torizo_Instr_10 },
  { fnTorizo_Instr_11, Torizo_Instr_11 },
  { fnTorizo_Instr_29, Torizo_Instr_29 },
  { fnTorizo_Instr_1, Torizo_Instr_1 },
  { fnTorizo_Instr_28, Torizo_Instr_28 },
  { fnTorizo_Instr_4, Torizo_Instr_4 },
  { fnTorizo_Instr_40, Torizo_Instr_40 },
  { fnTorizo_Instr_16, Torizo_Instr_16 },
  { fnTorizo_Instr_27, Torizo_Instr_27 },
  { fnTorizo_Instr_23, Torizo_Instr_23 },
  { fnTorizo_Instr_14, Torizo_Instr_14 },
  { fnTorizo_Instr_15, Torizo_Instr_15 },
  { fnTorizo_Instr_26, Torizo_Instr_26 },
  { fnTorizo_Instr_18, Torizo_Instr_18 },
  { fnTorizo_Instr_20, Torizo_Instr_20 },
  { fnTorizo_Instr_44, Torizo_Instr_44 },
  { fnTorizo_Instr_21, Torizo_Instr_21 },
  { fnTorizo_Instr_17, Torizo_Instr_17 },
  { fnTorizo_Instr_13, Torizo_Instr_13 },
  { fnTorizo_Instr_39, Torizo_Instr_39 },
  { fnTorizo_Instr_41, Torizo_Instr_41 },
  { fnTorizo_Instr_42, Torizo_Instr_42 },
  { fnTorizo_Instr_48, Torizo_Instr_48 },
  { fnTorizo_Instr_57, Torizo_Instr_57 },
  { fnTorizo_Instr_58, Torizo_Instr_58 },
  { fnTorizo_Instr_59, Torizo_Instr_59 },
  { fnTorizo_Instr_62, Torizo_Instr_62 },
  { fnTorizo_Instr_63, Torizo_Instr_63 },
  { fnTorizo_Instr_56, Torizo_Instr_56 },
  { fnTorizo_Instr_60, Torizo_Instr_60 },
  { fnTorizo_Instr_46, Torizo_Instr_46 },
  { fnTorizo_Instr_47, Torizo_Instr_47 },
  { fnTorizo_Instr_49, Torizo_Instr_49 },
  { fnTorizo_Instr_61, Torizo_Instr_61 },
  { fnTorizo_Instr_53, Torizo_Instr_53 },
  { fnTorizo_Instr_55, Torizo_Instr_55 },
  { fnTorizo_Instr_52, Torizo_Instr_52 },
  { fnTorizo_Instr_50, Torizo_Instr_50 },
  { fnTorizo_Instr_43, Torizo_Instr_43 },
  { fnTorizo_Instr_51, Torizo_Instr_51 },
  { fnTorizo_Instr_45, Torizo_Instr_45 },
  { fnTorizo_Instr_54, Torizo_Instr_54 },
  { fnShaktool_Instr_2, Shaktool_Instr_2 },
  { fnShaktool_Instr_3, Shaktool_Instr_3 },
  { fnShaktool_Instr_4, Shaktool_Instr_4 },
  { fnShaktool_Instr_5, Shaktool_Instr_5 },
  { fnShaktool_Instr_6, Shaktool_Instr_6 },
  { fnShaktool_Instr_1, Shaktool_Instr_1 },
  { fnShaktool_Instr_9, Shaktool_Instr_9 },
  { fnShaktool_Instr_11, Shaktool_Instr_11 },
  { fnShaktool_Instr_10, Shaktool_Instr_10 },
  { fnShaktool_Instr_8, Shaktool_Instr_8 },
  { fnShaktool_Instr_13, Shaktool_Instr_13 },
  { fnShaktool_Instr_12, Shaktool_Instr_12 },
  { fnShaktool_Instr_7, Shaktool_Instr_7 },
  { fnShaktool_Instr_14, Shaktool_Instr_14 },
  { fnSpacePirates_Instr_MovePixelsDownAndChangeDirFaceRight, SpacePirates_Instr_MovePixelsDownAndChangeDirFaceRight },
  { fnSpacePirates_Instr_MovePixelsDownAndChangeDirFaceLeft, SpacePirates_Instr_MovePixelsDownAndChangeDirFaceLeft },
  { fnSpacePirates_Instr_RandomNewDirFaceR, SpacePirates_Instr_RandomNewDirFaceR },
  { fnSpacePirates_Instr_RandomNewDirFaceL, SpacePirates_Instr_RandomNewDirFaceL },
  { fnSpacePirates_Instr_PrepareWallJumpR, SpacePirates_Instr_PrepareWallJumpR },
  { fnSpacePirates_Instr_PrepareWallJumpL, SpacePirates_Instr_PrepareWallJumpL },
  { fnSpacePirates_Instr_FireLaserL, SpacePirates_Instr_FireLaserL },
  { fnSpacePirates_Instr_FireLaserR, SpacePirates_Instr_FireLaserR },
  { fnSpacePirates_Instr_SetEnemyFunc, SpacePirates_Instr_SetEnemyFunc },
  { fnSpacePirates_Instr_PlaySfx, SpacePirates_Instr_PlaySfx },
  { fnSpacePirates_Instr_20, SpacePirates_Instr_20 },
  { fnSpacePirates_Instr_16, SpacePirates_Instr_16 },
  { fnSpacePirates_Instr_15, SpacePirates_Instr_15 },
  { fnSpacePirates_Instr_18, SpacePirates_Instr_18 },
  { fnSpacePirates_Instr_17, SpacePirates_Instr_17 },
  { fnSpacePirates_Instr_19, SpacePirates_Instr_19 },
  { fnSpacePirates_Instr_21, SpacePirates_Instr_21 },
  { fnSpacePirates_Instr_12, SpacePirates_Instr_12 },
  { fnSpacePirates_Instr_14, SpacePirates_Instr_14 },
  { fnSpacePirates_Instr_11, SpacePirates_Instr_11 },
  { fnSpacePirates_Instr_13, SpacePirates_Instr_13 },
  { fnBotwoon_Instr_1, Botwoon_Instr_1 },
  { fnBotwoon_Instr_2, Botwoon_Instr_2 },
  { fnBotwoon_Instr_3, Botwoon_Instr_3 },
  { fnBotwoon_Instr_4, Botwoon_Instr_4 },
  { fnBotwoon_Instr_5, Botwoon_Instr_5 },
  { fnBotwoon_Instr_6, Botwoon_Instr_6 },
  { fnBotwoon_Instr_7, Botwoon_Instr_7 },
  { fnBotwoon_Instr_8, Botwoon_Instr_8 },
  { fnBotwoon_Instr_9, Botwoon_Instr_9 },
  { fnBotwoon_Instr_10, Botwoon_Instr_10 },
  { fnBotwoon_Instr_SetSpitting, Botwoon_Instr_SetSpitting },
  { fnBotwoon_Instr_QueueSpitSfx, Botwoon_Instr_QueueSpitSfx },
  { fnEscapeEtecoon_Instr_1, EscapeEtecoon_Instr_1 },
  { fnEscapeEtecoon_Instr_2, EscapeEtecoon_Instr_2 },
  { fnEscapeDachora_Instr_2, EscapeDachora_Instr_2 },
  { fnEscapeDachora_Instr_3, EscapeDachora_Instr_3 },
  { fnEscapeDachora_Instr_1, EscapeDachora_Instr_1 },
  { fnEscapeDachora_Instr_4, EscapeDachora_Instr_4 },
};

static int CmpU32(const void *key, const void *elem) {
  uint32 want = *(const uint32 *)key;
  uint32 have = *(const uint32 *)elem; /* addr is the first field of each map row */
  return (want > have) - (want < have);
}

static EnemyAiFn LookupEnemyAi(uint32 ea) {
  ea = CanonicalizeEnemyHandler(ea);
  const EnemyAiAddrMap *hit = bsearch(&ea, kEnemyAiByAddr,
      sizeof(kEnemyAiByAddr) / sizeof(kEnemyAiByAddr[0]),
      sizeof(kEnemyAiByAddr[0]), CmpU32);
  return hit ? hit->fn : NULL;
}

EnemyAiFn EnemyAiFromAddr(uint32 ea) {
  EnemyAiFn fn = LookupEnemyAi(ea);
  if (!fn) {
    Unreachable();
    return EnemyAi_Nop;
  }
  return fn;
}

static EnemyPreInstrFn EnemyPreInstrFromAddr(uint32 ea) {
  ea = CanonicalizeEnemyHandler(ea);
  const EnemyPreInstrAddrMap *hit = bsearch(&ea, kEnemyPreInstrByAddr,
      sizeof(kEnemyPreInstrByAddr) / sizeof(kEnemyPreInstrByAddr[0]),
      sizeof(kEnemyPreInstrByAddr[0]), CmpU32);
  if (!hit) {
    Unreachable();
    return EnemyPreInstr_Nop;
  }
  return hit->fn;
}

static EnemyInstrFn EnemyInstrFromAddr(uint32 ea) {
  ea = CanonicalizeEnemyHandler(ea);
  const EnemyInstrAddrMap *hit = bsearch(&ea, kEnemyInstrByAddr,
      sizeof(kEnemyInstrByAddr) / sizeof(kEnemyInstrByAddr[0]),
      sizeof(kEnemyInstrByAddr[0]), CmpU32);
  if (!hit) {
    Unreachable();
    return NULL;
  }
  return hit->fn;
}

void BindEnemyDefAi(EnemyDef *ed, EnemyDefAiFns *fns) {
  uint32 bank;
  if (!ed || !fns)
    return;
  bank = (uint32)ed->bank << 16;
  fns->ai_init = ed->ai_init ? LookupEnemyAi(bank | ed->ai_init) : NULL;
  fns->main_ai = ed->main_ai ? LookupEnemyAi(bank | ed->main_ai) : NULL;
  fns->grapple_ai = ed->grapple_ai ? LookupEnemyAi(bank | ed->grapple_ai) : NULL;
  fns->hurt_ai = ed->hurt_ai ? LookupEnemyAi(bank | ed->hurt_ai) : NULL;
  fns->frozen_ai = ed->frozen_ai ? LookupEnemyAi(bank | ed->frozen_ai) : NULL;
  fns->time_is_frozen_ai = ed->time_is_frozen_ai ? LookupEnemyAi(bank | ed->time_is_frozen_ai) : NULL;
  fns->powerbomb_reaction = LookupEnemyAi(bank | (ed->powerbomb_reaction ? ed->powerbomb_reaction : 0x8037));
  fns->touch_ai = ed->touch_ai ? LookupEnemyAi(bank | ed->touch_ai) : NULL;
  fns->shot_ai = ed->shot_ai ? LookupEnemyAi(bank | ed->shot_ai) : NULL;
}

void EnemyRunPreInstr(uint16 off) {
  EnemyData *E = gEnemyData(cur_enemy_index);
  EnemyPreInstrFromAddr(((uint32)E->bank << 16) | off)(cur_enemy_index);
}

const uint16 *EnemyRunInstr(uint16 opcode, uint16 k, const uint16 *j) {
  EnemyData *E = gEnemyData(k);
  EnemyInstrFn fn = EnemyInstrFromAddr(((uint32)E->bank << 16) | opcode);
  return fn ? fn(k, j) : 0;
}

