#ifndef EPROJ_INTERNAL_H_
#define EPROJ_INTERNAL_H_

#include "types.h"

void CallEprojPreInstr(uint32 ea, uint16 k);
const uint8 *CallEprojInstr(uint32 ea, uint16 k, const uint8 *j);
void CallEprojInit(uint32 ea, uint16 j);

uint16 CheckIfEprojIsOffScreen(uint16 k);
void EprojInit_TourianEscapeShaftFakeWallExplode(uint16 j);
void EprojInit_LavaSeahorseFireball(uint16 j);
void sub_86B535(uint16 k);
void EprojInit_EyeDoorProjectile(uint16 j);
void EprojInit_EyeDoorSweat(uint16 j);
void EprojPreInstr_EyeDoorProjectile(uint16 k);
void EprojPreInstr_EyeDoorSweat(uint16 k);
void EprojInit_NuclearWaffleBody(uint16 j);
void EprojInit_NorfairLavaquakeRocks(uint16 j);
void EprojInit_NamiFuneFireball(uint16 j);
void EprojPreInstr_NamiFuneFireball(uint16 k);
void EprojInit_LavaThrownByLavaman(uint16 j);
void sub_86E049(uint16 k);
void EprojInit_DustCloudOrExplosion(uint16 j);
void EprojPreInstr_DustCloudOrExplosion(uint16 k);
void EprojInit_EyeDoorSmoke(uint16 j);
void EprojInit_SpawnedShotGate(uint16 j);
void EprojInit_ClosedDownwardsShotGate(uint16 j);
void EprojInit_ClosedUpwardsShotGate(uint16 j);
void EprojPreInstr_E605(uint16 k);
void EprojInit_SaveStationElectricity(uint16 j);
void EprojPreInstr_NorfairLavaquakeRocks(uint16 k);
void EprojPreInstr_NorfairLavaquakeRocks_Inner(uint16 k);
const uint8 *EprojInstr_Earthquake(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SpawnTourianStatueUnlockingParticleTail(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_AddToYpos(uint16 k, const uint8 *epjp);
void EprojInit_TourianStatueUnlockingParticleWaterSplash(uint16 j);
void EprojInit_TourianStatueEyeGlow(uint16 j);
void EprojInit_TourianStatueUnlockingParticle(uint16 j);
void EprojIni_TourianStatueUnlockingParticleTail(uint16 j);
void EprojInit_TourianStatueSoul(uint16 j);
void EprojInit_TourianStatueBaseDecoration(uint16 j);
void EprojInit_TourianStatueRidley(uint16 j);
void EprojInit_TourianStatuePhantoon(uint16 j);
void EprojPreInstr_TourianStatueUnlockingParticleWaterSplash(uint16 k);
void EprojPreInstr_TourianStatueUnlockingParticle(uint16 k);
void EprojPreInstr_TourianStatueSoul(uint16 k);
void EprojPreInstr_BA42(uint16 k);
void EprojPreInstr_TourianStatueStuff(uint16 k);
void EprojInit_MotherBrainRoomTurrets(uint16 j);
void EprojInit_MotherBrainRoomTurretBullets(uint16 j);
void EprojPreInstr_MotherBrainRoomTurrets(uint16 k);
void EprojPreInstr_MotherBrainRoomTurretBullets(uint16 k);
void EprojPreInstr_MotherBrainBomb(uint16 k);
const uint8 *EprojInstr_SwitchJump(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_UserPalette0(uint16 k, const uint8 *epjp);
void Eproj_MotherBrainsBlueRingLasers(uint16 j);
void Eproj_MoveToBlueRingSpawnPosition(uint16 k);
void EprojInit_MotherBrainBomb(uint16 j);
void sub_86C605(uint16 j);
void EprojInit_MotherBrainDeathBeemFired(uint16 j);
void SpawnMotherBrainDeathBeam(uint16 k);
void EprojPreInstr_MotherBrainRainbowBeam(uint16 k);
void EprojInit_MotherBrainRainbowBeam(uint16 j);
void EprojPreInstr_C84D(uint16 k);
void EprojInit_MotherBrainsDrool(uint16 j);
void EprojInit_MotherBrainsDrool_Falling(uint16 k);
const uint8 *EprojInstr_Add12ToY(uint16 k, const uint8 *epjp);
void EprojPreInit_MotherBrainsDeathExplosion_0(uint16 k);
void EprojInit_MotherBrainsDeathExplosion(uint16 j);
void EprojInit_MotherBrainsRainbowBeamExplosion(uint16 j);
void EprojPreInstr_MotherBrainsRainbowBeamExplosion(uint16 k);
void EprojInit_MotherBrainEscapeDoorParticles(uint16 j);
void EprojPreInstr_MotherBrainsExplodedDoorParticles(uint16 k);
void EprojInit_MotherBrainPurpleBreathBig(uint16 j);
void EprojInit_MotherBrainPurpleBreathSmall(uint16 j);
const uint8 *EprojInstr_MotherBrainPurpleBreathIsActive(uint16 k, const uint8 *epjp);
void EprojPreInstr_TimeBombSetJapaneseText(uint16 k);
void EprojInit_TimeBombSetJapaneseText(uint16 j);
void EprojInit_MotherBrainTubeFalling(uint16 j);
void EprojPreInstr_MotherBrainTubeFalling(uint16 k);
void MotherBrainTubeFallingFunc_GenerateExplosion(uint16 k);
void MotherBrainTubeFallingFunc_Falling(uint16 k);
void EprojInit_MotherBrainGlassShatteringShard(uint16 j);
void EprojInit_MotherBrainGlassShatteringSparkle(uint16 j);
void EprojPreInstr_MotherBrainGlassShatteringShard(uint16 k);

const uint8 *EprojInstr_Delete(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_Sleep(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetPreInstr_(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_ClearPreInstr(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_CallFunc(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_Goto(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_GotoRel(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DecTimerAndGotoIfNonZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DecTimerAndGotoRelIfNonZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetTimer(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_MoveRandomlyWithinRadius(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetProjectileProperties(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_ClearProjectileProperties(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_EnableCollisionWithSamusProj(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DisableCollisionWithSamusProj(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DisableCollisionWithSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_EnableCollisionWithSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetToNotDieOnContact(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetToDieOnContact(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetLowPriority(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetHighPriority(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetXyRadius(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetXyRadiusZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_CalculateDirectionTowardsSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_WriteColorsToPalette(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueMusic(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max1(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max1(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max1(uint16 k, const uint8 *epjp);

#endif
