#ifndef EPROJ_INTERNAL_H_
#define EPROJ_INTERNAL_H_

#include "types.h"

void CallEprojPreInstr(uint32 ea, uint16 k);
const uint8 *CallEprojInstr(uint32 ea, uint16 k, const uint8 *j);
void CallEprojInit(uint32 ea, uint16 j);

uint16 CheckIfEprojIsOffScreen(uint16 k);
void EprojInit_TourianEscapeShaftFakeWallExplode(uint16 j);
void EprojInit_LavaSeahorseFireball(uint16 j);
void sub_86B535(uint16 k);
void EprojInit_EyeDoorProjectile(uint16 j);
void EprojInit_EyeDoorSweat(uint16 j);
void EprojPreInstr_EyeDoorProjectile(uint16 k);
void EprojPreInstr_EyeDoorSweat(uint16 k);
void EprojInit_NuclearWaffleBody(uint16 j);
void EprojInit_NorfairLavaquakeRocks(uint16 j);
void EprojInit_NamiFuneFireball(uint16 j);
void EprojPreInstr_NamiFuneFireball(uint16 k);
void EprojInit_LavaThrownByLavaman(uint16 j);
void sub_86E049(uint16 k);
void EprojInit_DustCloudOrExplosion(uint16 j);
void EprojPreInstr_DustCloudOrExplosion(uint16 k);
void EprojInit_EyeDoorSmoke(uint16 j);
void EprojInit_SpawnedShotGate(uint16 j);
void EprojInit_ClosedDownwardsShotGate(uint16 j);
void EprojInit_ClosedUpwardsShotGate(uint16 j);
void EprojPreInstr_E605(uint16 k);
void EprojInit_SaveStationElectricity(uint16 j);
void EprojPreInstr_NorfairLavaquakeRocks(uint16 k);
void EprojPreInstr_NorfairLavaquakeRocks_Inner(uint16 k);
const uint8 *EprojInstr_Earthquake(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SpawnTourianStatueUnlockingParticleTail(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_AddToYpos(uint16 k, const uint8 *epjp);
void EprojInit_TourianStatueUnlockingParticleWaterSplash(uint16 j);
void EprojInit_TourianStatueEyeGlow(uint16 j);
void EprojInit_TourianStatueUnlockingParticle(uint16 j);
void EprojIni_TourianStatueUnlockingParticleTail(uint16 j);
void EprojInit_TourianStatueSoul(uint16 j);
void EprojInit_TourianStatueBaseDecoration(uint16 j);
void EprojInit_TourianStatueRidley(uint16 j);
void EprojInit_TourianStatuePhantoon(uint16 j);
void EprojPreInstr_TourianStatueUnlockingParticleWaterSplash(uint16 k);
void EprojPreInstr_TourianStatueUnlockingParticle(uint16 k);
void EprojPreInstr_TourianStatueSoul(uint16 k);
void EprojPreInstr_BA42(uint16 k);
void EprojPreInstr_TourianStatueStuff(uint16 k);
void EprojInit_MotherBrainRoomTurrets(uint16 j);
void EprojInit_MotherBrainRoomTurretBullets(uint16 j);
void EprojPreInstr_MotherBrainRoomTurrets(uint16 k);
void EprojPreInstr_MotherBrainRoomTurretBullets(uint16 k);
void EprojPreInstr_MotherBrainBomb(uint16 k);
const uint8 *EprojInstr_SwitchJump(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_UserPalette0(uint16 k, const uint8 *epjp);
void Eproj_MotherBrainsBlueRingLasers(uint16 j);
void Eproj_MoveToBlueRingSpawnPosition(uint16 k);
void EprojInit_MotherBrainBomb(uint16 j);
void sub_86C605(uint16 j);
void EprojInit_MotherBrainDeathBeemFired(uint16 j);
void SpawnMotherBrainDeathBeam(uint16 k);
void EprojPreInstr_MotherBrainRainbowBeam(uint16 k);
void EprojInit_MotherBrainRainbowBeam(uint16 j);
void EprojPreInstr_C84D(uint16 k);
void EprojInit_MotherBrainsDrool(uint16 j);
void EprojInit_MotherBrainsDrool_Falling(uint16 k);
const uint8 *EprojInstr_Add12ToY(uint16 k, const uint8 *epjp);
void EprojPreInit_MotherBrainsDeathExplosion_0(uint16 k);
void EprojInit_MotherBrainsDeathExplosion(uint16 j);
void EprojInit_MotherBrainsRainbowBeamExplosion(uint16 j);
void EprojPreInstr_MotherBrainsRainbowBeamExplosion(uint16 k);
void EprojInit_MotherBrainEscapeDoorParticles(uint16 j);
void EprojPreInstr_MotherBrainsExplodedDoorParticles(uint16 k);
void EprojInit_MotherBrainPurpleBreathBig(uint16 j);
void EprojInit_MotherBrainPurpleBreathSmall(uint16 j);
const uint8 *EprojInstr_MotherBrainPurpleBreathIsActive(uint16 k, const uint8 *epjp);
void EprojPreInstr_TimeBombSetJapaneseText(uint16 k);
void EprojInit_TimeBombSetJapaneseText(uint16 j);
void EprojInit_MotherBrainTubeFalling(uint16 j);
void EprojPreInstr_MotherBrainTubeFalling(uint16 k);
void MotherBrainTubeFallingFunc_GenerateExplosion(uint16 k);
void MotherBrainTubeFallingFunc_Falling(uint16 k);
void EprojInit_MotherBrainGlassShatteringShard(uint16 j);
void EprojInit_MotherBrainGlassShatteringSparkle(uint16 j);
void EprojPreInstr_MotherBrainGlassShatteringShard(uint16 k);

const uint8 *EprojInstr_Delete(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_Sleep(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetPreInstr_(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_ClearPreInstr(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_CallFunc(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_Goto(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_GotoRel(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DecTimerAndGotoIfNonZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DecTimerAndGotoRelIfNonZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetTimer(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_MoveRandomlyWithinRadius(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetProjectileProperties(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_ClearProjectileProperties(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_EnableCollisionWithSamusProj(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DisableCollisionWithSamusProj(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_DisableCollisionWithSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_EnableCollisionWithSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetToNotDieOnContact(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetToDieOnContact(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetLowPriority(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetHighPriority(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetXyRadius(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetXyRadiusZero(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_CalculateDirectionTowardsSamus(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_WriteColorsToPalette(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueMusic(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max15(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx1_Max1(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_Max1(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx3_Max1(uint16 k, const uint8 *epjp);

void Eproj_Init_0x8aaf(uint16 j);
void Eproj_PreInit_0x8aaf(uint16 k);
void Eproj_Init_0x8bc2_SkreeDownRight(uint16 j);
void Eproj_Init_0x8bd0_SkreeUpRight(uint16 j);
void Eproj_Init_0x8bde_SkreeDownLeft(uint16 j);
void Eproj_Init_0x8bec_SkreeUpLeft(uint16 j);
void Eproj_PreInstr_SkreeParticle(uint16 k);

const uint8 *EprojInstr_SpawnEnemyDropsWithDraygonsEyeDrops(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetPreInstrA(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetPreInstrB(uint16 k, const uint8 *epjp);
void EprojInit_DraygonsGunk(uint16 j);
void EprojInit_DraygonsWallTurretProjs(uint16 j);
void EprojPowerBombCollision(uint16 k);
const uint8 *EprojInstr_868D99(uint16 k, const uint8 *epjp);
void EprojPreInstr_8DCA(uint16 k);
void EprojPreInstr_DraygonsTurret_8DFF(uint16 k);
void EprojPreInstr_DraygonsGunk_8E0F(uint16 k);

void EprojInit_CrocomireProjectile(uint16 j);
void EprojPreInstr_CrocomireProjectile(uint16 k);
void sub_8690B3(uint16 k);
void EprojInit_CrocomireSpikeWallPieces(uint16 j);
void EprojPreInstr_CrocomireSpikeWallPieces(uint16 k);
const uint8 *EprojInstr_9270(uint16 k, const uint8 *epjp);
void EprojInit_CrocomireBridgeCrumbling(uint16 j);
void EprojPreInstr_CrocomireBridgeCrumbling(uint16 k);

void EprojInit_9634(uint16 j);
void EprojPreInstr_9634(uint16 k);
void EprojInit_9642_RidleysFireball(uint16 j);
void EprojPreInstr_9642_RidleysFireball(uint16 k);
const uint8 *EprojInstr_DisableCollisionsWithSamus(uint16 k, const uint8 *epjp);
void EprojInit_9660_FireballExplosion(uint16 j);
void EprojInit_9688(uint16 j);
void EprojInit_9696(uint16 j);
void EprojInit_966C(uint16 j);
void EprojInit_967A(uint16 j);
void EprojPreInstr_966C(uint16 k);
void EprojPreInstr_9688(uint16 k);
void EprojPreInstr_96A4(uint16 k);
void EprojPreInstr_96C0(uint16 k);
void EprojPreInstr_96CE(uint16 k);
const uint8 *EprojInstr_95BA(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_95ED(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_9620(uint16 k, const uint8 *epjp);
void EprojInit_9734_CeresFallingDebris(uint16 j);
void EprojPreInstr_9734_CeresFallingDebris(uint16 k);
const uint8 *EprojInstr_980E(uint16 k, const uint8 *epjp);
void EprojInit_PirateMotherBrainLaser(uint16 j);
const uint8 *EprojInstr_SetPreInstrAndRun(uint16 k, const uint8 *epjp);
void EprojPreInstr_PirateMotherBrainLaser_MoveLeft(uint16 k);
void EprojPreInstr_PirateMotherBrainLaser_MoveRight(uint16 k);
void EprojInit_PirateClaw(uint16 j);
void EprojPreInstr_PirateClawThrownLeft(uint16 k);
void EprojPreInstr_PirateClawThrownRight(uint16 k);
void EprojInit_A379(uint16 j);
void EprojInit_CeresElevatorPad(uint16 j);
void sub_86A301(uint16 j);
void EprojInit_CeresElevatorPlatform(uint16 j);
void EprojPreInstr_CeresElevatorPad(uint16 k);
void EprojPreInstr_CeresElevatorPlatform(uint16 k);
void EprojPreInstr_PrePhantomRoom(uint16 j);
const uint8 *EprojInstr_A3BE(uint16 k, const uint8 *epjp);
void EprojInit_BDA2(uint16 j);
void EprojInit_ShaktoolAttackMiddleBackCircle(uint16 j);
void EprojInit_ShaktoolAttackFrontCircle(uint16 v1);
void EprojPreInstr_BE12(uint16 k);

void EprojInit_RocksKraidSpits(uint16 j);
void EprojInit_RocksFallingKraidCeiling(uint16 j);
void EprojInit_RocksWhenKraidRises(uint16 j);
void EprojPreInstr_KraidRocks(uint16 k);
void EprojPreInstr_RocksFallingKraidCeiling(uint16 k);
void sub_869DA5(uint16 k);
void EprojInit_MiniKraidSpit(uint16 j);
void EprojPreInit_MiniKraidSpit(uint16 k);
void EprojInit_MiniKraidSpikesLeft(uint16 j);
void EprojInit_MiniKraidSpikesRight(uint16 j);
void EprojPreInstr_MiniKraidSpikes(uint16 k);

void EprojInit_KiHunterAcidSpitLeft(uint16 j);
void EprojInit_KiHunterAcidSpitRight(uint16 j);
void sub_86CFD5(uint16 k);
void sub_86CFE6(uint16 k);
void sub_86CFF8(uint16 k);
void EprojInit_KagosBugs(uint16 j);
void EprojPreInstr_KagosBugs_Func1(uint16 k);
void EprojPreInstr_KagosBugs_Func2(uint16 k);
void EprojPreInstr_KagosBugs(uint16 k);
void EprojPreInstr_D0EC(uint16 k);
void EprojPreInstr_D128(uint16 v0);
const uint8 *EprojInstr_D15C(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_D1B6(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_D1C7(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_D1CE(uint16 k, const uint8 *epjp);
void EprojInit_MaridiaFloatersSpikes(uint16 j);
void EprojPreInstr_MaridiaFloatersSpikes(uint16 k);
void EprojInit_WreckedShipRobotLaserDown(uint16 j);
void EprojInit_WreckedShipRobotLaserHorizontal(uint16 j);
void EprojInit_WreckedShipRobotLaserUp(uint16 j);
void EprojPreInstr_WreckedShipRobotLaser(uint16 k);
const uint8 *EprojInstr_AssignNewN00bTubeShardVelocity(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetN00bTubeShardX(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_D62A(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SetXvelRandom(uint16 k, const uint8 *epjp);
void EprojInit_N00bTubeCrack(uint16 j);
void EprojInit_N00bTubeShards(uint16 j);
void EprojInit_N00bTubeReleasedAirBubbles(uint16 j);
void sub_86D7BF(uint16 k);
void sub_86D7DE(uint16 k);
void EprojPreInstr_N00bTubeShards(uint16 k);
void sub_86D83D(uint16 k);
void sub_86D89F(uint16 k);
void sub_86D8DF(uint16 k);
void sub_86D992(uint16 v0);
void EprojPreInstr_SpikeShootingPlantSpikes_MoveY1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_MoveY2(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_MoveX1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_MoveX2(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_0_MoveX1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_2_MoveX2(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_1_MoveY1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_4_MoveY2(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_6_MoveX1Y1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_8_MoveX1Y2(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_7_MoveX2Y1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes_9_MoveX2Y2(uint16 k);
void EprojPreInstrHelper_SpikeShootingPlantSpikes_Func1(uint16 k);
void EprojPreInstr_SpikeShootingPlantSpikes(uint16 k);
uint16 EprojPreInstrHelper_SpikeShootingPlantSpikes_Func2(uint16 k);
void EprojInit_DBF2(uint16 j);
void EprojPreInstr_DBF2_Func1(uint16 k);
void EprojPreInstr_DBF2(uint16 k);
void EprojPreInstr_DBF2_MoveX1(uint16 k);
void EprojPreInstr_DBF2_MoveX2(uint16 k);
uint16 EprojPreInstrHelper_DBF2_Func2(uint16 k);
const uint8 *EprojInstr_DC5A(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SpawnEnemyDrops_0(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_SpawnSporesEproj(uint16 k, const uint8 *epjp);
void EprojInit_Spores(uint16 j);
void EprojInit_SporeSpawnStalk(uint16 j);
void sub_86DCC3(uint16 v0);
void EprojInit_SporeSpawners(uint16 j);
void EprojPreInstr_Spores(uint16 k);
void EprojPreInstr_SporeSpawners(uint16 k);
const uint8 *EprojInstr_DFEA(uint16 k, const uint8 *epjp);

void EprojInit_BotwoonsBody(uint16 j);
void CallBotwoonEprojFunc(uint32 ea, uint16 k);
void EprojPreInstr_BotwoonsBody(uint16 k);
void Eproj_BotwoonsBody_Main(uint16 k);
void Eproj_BotwoonsBodyHurtFlashHandling1(uint16 k);
void Eproj_BotwoonsBodyHurtFlashHandling2(uint16 j);
void Eproj_BotwonsBodyFunction_Dying(uint16 v0);
void Eproj_BotwonsBodyFunction_Dying2(uint16 v0);
void Eproj_BotwonsBodyFunction_DyingFalling(uint16 v0);
void QueueSmallExplosionSfx(void);
void EprojInit_BotwoonsSpit(uint16 j);
void EprojPreInstr_BotwoonsSpit(uint16 k);
void sub_86EC0C(uint16 k);
uint16 sub_86EC18(uint16 k);
void EprojInit_YappingMawsBody(uint16 j);

const uint8 *EprojInstr_ECE3(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_ED17(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_9(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_24(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_QueueSfx2_B(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_EEAF(uint16 k, const uint8 *epjp);
const uint8 *EprojInstr_HandleRespawningEnemy(uint16 k, const uint8 *epjp);
void EprojInit_F337(uint16 j);
void EprojInit_EnemyDeathExplosion(uint16 j);
void EprojPreInstr_Pickup(uint16 k);
void Eproj_Pickup_SmallHealth(void);
void Eproj_Pickup_BigHealth(void);
void Eproj_Pickup_PowerBombs(void);
void Eproj_Pickup_Missiles(void);
void Eproj_Pickup_SuperMissiles(void);
uint16 RandomDropRoutine(uint16 k);
void RespawnEnemy(uint16 v0);
void EprojInit_Sparks(uint16 j);
void EprojPreInstr_Sparks(uint16 k);

#endif
